#!/usr/bin/env python
# encoding: utf-8

name = "R_Addition_COm/groups"
shortDesc = ""
longDesc = """

"""

template(reactants=["Root"], products=["YC.=O"], ownReverse=False)

reverse = "COM_Elimination_From_Carbonyl"
reversible = True

reactantNum = 2

productNum = 1

autoGenerated = True

recipe(actions=[
    ['LOSE_PAIR', '*1', '1'],
    ['CHANGE_BOND', '*1', -1, '*3'],
    ['GAIN_PAIR', '*3', '1'],
    ['GAIN_RADICAL', '*1', '1'],
    ['FORM_BOND', '*1', 1, '*2'],
    ['LOSE_RADICAL', '*2', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 R    u1
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_3R->O",
    group = 
"""
1 *1 C2tc u0 p1 c-1 r0 {2,T}
2 *3 O4tc u0 p1 c+1 r0 {1,T}
3 *2 O    u1
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_N-3R->O",
    group = 
"""
1 *1 C2tc                     u0 p1 c-1 {2,T}
2 *3 O4tc                     u0 p1 c+1 {1,T}
3 *2 [C,Si,H,S,N,P,F,I,Br,Cl] u1
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_N-3R->O_3BrCClFHINPSSi->Br",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 Br   u1
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br",
    group = 
"""
1 *1 C2tc       u0 p1 c-1 {2,T}
2 *3 O4tc       u0 p1 c+1 {1,T}
3 *2 [C,S,Cl,H] u1
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_3CClHS->Cl",
    group = 
"""
1 *1 C2tc u0 p1 c-1 r0 {2,T}
2 *3 O4tc u0 p1 c+1 r0 {1,T}
3 *2 Cl   u1
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl",
    group = 
"""
1 *1 C2tc    u0 p1 c-1 {2,T}
2 *3 O4tc    u0 p1 c+1 {1,T}
3 *2 [C,S,H] u1
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_3CHS-inRing",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r1
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_3CHS-inRing_Ext-3CHS-R_4R!H->O",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r1 {4,[S,D,T,B,Q]}
4    O    u0 r1 {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_3CHS-inRing_Ext-3CHS-R_N-4R!H->O",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r1 {4,[S,D,T,B,Q]}
4    C    u0 r1 {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing",
    group = 
"""
1 *1 C2tc    u0 p1 c-1 {2,T}
2 *3 O4tc    u0 p1 c+1 {1,T}
3 *2 [C,S,H] u1 r0
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_3CHS->S",
    group = 
"""
1 *1 C2tc u0 p1 c-1 r0 {2,T}
2 *3 O4tc u0 p1 c+1 r0 {1,T}
3 *2 S    u1 r0
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S",
    group = 
"""
1 *1 C2tc  u0 p1 c-1 {2,T}
2 *3 O4tc  u0 p1 c+1 {1,T}
3 *2 [C,H] u1 r0
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r0 {4,[S,D,T,B,Q]}
4    R!H  ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r0 {4,[S,D,T,B,Q]}
4    C    ux {3,[S,D,T,B,Q]} {5,[S,D,T,B,Q]}
5    R!H  ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R_Ext-3CH-R",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r0 {4,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
4    C    ux {3,[S,D,T,B,Q]} {5,[S,D,T,B,Q]}
5    R!H  ux {4,[S,D,T,B,Q]}
6    F    ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R_Ext-3CH-R_5R!H->O",
    group = 
"""
1 *1 C2tc u0 p1 c-1 r0 {2,T}
2 *3 O4tc u0 p1 c+1 r0 {1,T}
3 *2 C    u1 r0 {4,[S,D,T,B,Q]} {6,S}
4    C    u0 r0 {3,[S,D,T,B,Q]} {5,[S,D,T,B,Q]}
5    O    ux {4,[S,D,T,B,Q]}
6    F    u0 r0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R_Ext-3CH-R_N-5R!H->O",
    group = 
"""
1 *1 C2tc  u0 p1 c-1 {2,T}
2 *3 O4tc  u0 p1 c+1 {1,T}
3 *2 C     u1 r0 {4,S} {6,[S,D,T,B,Q]}
4    C     ux {3,S} {5,S}
5    [F,C] u0 {4,S}
6    F     ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R_Ext-3CH-R_N-5R!H->O_5CF->C",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r0 {4,S} {6,[S,D,T,B,Q]}
4    C    ux {3,S} {5,S}
5    C    u0 r0 {4,S}
6    F    ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R_Ext-3CH-R_N-5R!H->O_N-5CF->C",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r0 {4,S} {6,[S,D,T,B,Q]}
4    C    ux {3,S} {5,S}
5    F    u0 r0 {4,S}
6    F    ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Sp-4R!H=3CCHH",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r0 {4,D}
4    R!H  u0 {3,D}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Sp-4R!H=3CCHH_Ext-3CH-R",
    group = 
"""
1 *1 C2tc u0 p1 c-1 r0 {2,T}
2 *3 O4tc u0 p1 c+1 r0 {1,T}
3 *2 C    u1 r0 {4,D} {5,[S,D,T,B,Q]}
4    R!H  u0 r0 {3,D}
5    R!H  ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_N-Sp-4R!H=3CCHH",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r0 {4,S}
4    R!H  ux {3,S}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_N-Sp-4R!H=3CCHH_Ext-3CH-R",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r0 {4,S} {5,[S,D,T,B,Q]}
4    R!H  ux {3,S}
5    R!H  ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_N-Sp-4R!H=3CCHH_Ext-3CH-R_Ext-3CH-R",
    group = 
"""
1 *1 C2tc u0 p1 c-1 {2,T}
2 *3 O4tc u0 p1 c+1 {1,T}
3 *2 C    u1 r0 {4,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
4    R!H  ux {3,S}
5    R!H  ux {3,[S,D,T,B,Q]}
6    R!H  ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_3CH->C",
    group = 
"""
1 *1 C2tc u0 p1 c-1 r0 {2,T}
2 *3 O4tc u0 p1 c+1 r0 {1,T}
3 *2 C    u1 r0
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_N-3CH->C",
    group = 
"""
1 *1 C2tc u0 p1 c-1 r0 {2,T}
2 *3 O4tc u0 p1 c+1 r0 {1,T}
3 *2 H    u1 r0
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_3R->O
    L2: Root_N-3R->O
        L3: Root_N-3R->O_3BrCClFHINPSSi->Br
        L3: Root_N-3R->O_N-3BrCClFHINPSSi->Br
            L4: Root_N-3R->O_N-3BrCClFHINPSSi->Br_3CClHS->Cl
            L4: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl
                L5: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_3CHS-inRing
                    L6: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_3CHS-inRing_Ext-3CHS-R_4R!H->O
                    L6: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_3CHS-inRing_Ext-3CHS-R_N-4R!H->O
                L5: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing
                    L6: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_3CHS->S
                    L6: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S
                        L7: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R
                            L8: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R
                                L9: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R_Ext-3CH-R
                                    L10: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R_Ext-3CH-R_5R!H->O
                                    L10: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R_Ext-3CH-R_N-5R!H->O
                                        L11: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R_Ext-3CH-R_N-5R!H->O_5CF->C
                                        L11: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Ext-4R!H-R_Ext-3CH-R_N-5R!H->O_N-5CF->C
                            L8: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Sp-4R!H=3CCHH
                                L9: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_Sp-4R!H=3CCHH_Ext-3CH-R
                            L8: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_N-Sp-4R!H=3CCHH
                                L9: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_N-Sp-4R!H=3CCHH_Ext-3CH-R
                                    L10: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_Ext-3CH-R_N-Sp-4R!H=3CCHH_Ext-3CH-R_Ext-3CH-R
                        L7: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_3CH->C
                        L7: Root_N-3R->O_N-3BrCClFHINPSSi->Br_N-3CClHS->Cl_N-3CHS-inRing_N-3CHS->S_N-3CH->C
"""
)

forbidden(
    label = "Frad",
    group = 
"""
1 *2 F u1 p3
""",
    shortDesc = """""",
    longDesc = 
"""
Could not find the TS
""",
)

forbidden(
    label = "O2_birad",
    group = 
"""
1 *2 O u1 p2 {2,S}
2    O u1 p2 {1,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

