#!/usr/bin/env python
# encoding: utf-8

name = "PFAS_HPL"

autoGenerated=False

entry(
    index = 0,
    label = "CF2H <=> CF+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.01E+12,'1/s'), n=0.49, Ea=(72977.06,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF2H <=> CF+HF""",
)
 
entry(
    index = 1,
    label = "CF3H <=> CF3+H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.53E+15,'1/s'), n=0.33, Ea=(106892.36,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3H <=> CF3+H""",
)
 
entry(
    index = 2,
    label = "CF3H <=> F+CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.00E+18,'1/s'), n=-0.61, Ea=(127284.60,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3H <=> F+CF2H""",
)
 
entry(
    index = 3,
    label = "CF3H <=> CF2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.66E+07,'1/s'), n=2.01, Ea=(71629.00,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3H <=> CF2+HF""",
)
 
entry(
    index = 4,
    label = "CF4+H <=> CF3+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.51E+04,'cm^3/(mol*s)'), n=2.95, Ea=(40266.52,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF4+H <=> CF3+HF""",
)
 
entry(
    index = 5,
    label = "CF4+H2O <=> CF3OH+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.89E+01,'cm^3/(mol*s)'), n=3.22, Ea=(86267.99,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF4+H2O <=> CF3OH+HF""",
)
 
entry(
    index = 6,
    label = "CF2O+H2O <=> FC(O)OH+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.42E-01,'cm^3/(mol*s)'), n=3.33, Ea=(35135.33,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF2O+H2O <=> FC(O)OH+HF""",
)
 
entry(
    index = 7,
    label = "CF3O <=> CF2O+F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.04E+12,'1/s'), n=0.23, Ea=(27498.24,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3O <=> CF2O+F""",
)
 
entry(
    index = 8,
    label = "CF3OH <=> CF2O+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.00E-06,'1/s'), n=5.46, Ea=(35158.88,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OH <=> CF2O+HF""",
)
 
entry(
    index = 9,
    label = "FCO2 <=> CO2+F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.06E+10,'1/s'), n=1.06, Ea=(16429.53,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is FCO2 <=> CO2+F""",
)
 
entry(
    index = 10,
    label = "FC(O)OH <=> CO2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.53E+04,'1/s'), n=2.53, Ea=(28082.11,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is FC(O)OH <=> CO2+HF""",
)
 
entry(
    index = 11,
    label = "CF3OO <=> CF3+O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.24E+22,'1/s'), n=-1.75, Ea=(70422.24,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OO <=> CF3+O2""",
)
 
entry(
    index = 12,
    label = "CF3OO <=> CF2O+OF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.57E+12,'1/s'), n=0.68, Ea=(97093.52,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OO <=> CF2O+OF""",
)
 
entry(
    index = 13,
    label = "CF3CF <=> CF2CF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.40E+10,'1/s'), n=0.81, Ea=(42007.76,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CF <=> CF2CF2""",
)
 
entry(
    index = 14,
    label = "CF3CF <=> CF3+CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.54E+21,'1/s'), n=-1.47, Ea=(70284.78,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CF <=> CF3+CF""",
)
 
entry(
    index = 15,
    label = "CF3CF2 <=> CF4+CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.44E+10,'1/s'), n=1.13, Ea=(110322.43,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CF2 <=> CF4+CF""",
)
 
entry(
    index = 16,
    label = "CF3CF2H <=> CF3+CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.12E+24,'1/s'), n=-2.12, Ea=(97427.75,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CF2H <=> CF3+CF2H""",
)
 
entry(
    index = 17,
    label = "CF3CF2H <=> CF2CF2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.31E-23,'1/s'), n=10.54, Ea=(68887.07,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CF2H <=> CF2CF2+HF""",
)
 
entry(
    index = 18,
    label = "CF3CF2H <=> CF3CF2+H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.05E+14,'1/s'), n=0.42, Ea=(103655.37,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CF2H <=> CF3CF2+H""",
)
 
entry(
    index = 19,
    label = "CF3CF2H <=> F+CF2CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.91E+18,'1/s'), n=-0.71, Ea=(126135.30,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CF2H <=> F+CF2CF2H""",
)
 
entry(
    index = 20,
    label = "C2F6 <=> CF3+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.58E+26,'1/s'), n=-2.35, Ea=(99025.11,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F6 <=> CF3+CF3""",
)
 
entry(
    index = 21,
    label = "C2F6 <=> CF3CF2+F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.57E+19,'1/s'), n=-0.75, Ea=(125644.99,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F6 <=> CF3CF2+F""",
)
 
entry(
    index = 22,
    label = "C2F6 <=> CF4+CF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.74E+11,'1/s'), n=0.9, Ea=(119826.16,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F6 <=> CF4+CF2""",
)
 
entry(
    index = 23,
    label = "C2F6+H <=> CF3CF2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.26E+04,'cm^3/(mol*s)'), n=3.06, Ea=(36033.64,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F6+H <=> CF3CF2+HF""",
)
 
entry(
    index = 24,
    label = "C2F6+H2O <=> C2F5OH+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.98E+00,'cm^3/(mol*s)'), n=3.36, Ea=(80307.59,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F6+H2O <=> C2F5OH+HF""",
)
 
entry(
    index = 25,
    label = "CF2CFO <=> CF2O+CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.27E+10,'1/s'), n=0.64, Ea=(78811.39,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF2CFO <=> CF2O+CF""",
)
 
entry(
    index = 26,
    label = "F2COCF <=> CF2CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.61E+12,'1/s'), n=0.69, Ea=(59688.46,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is F2COCF <=> CF2CFO""",
)
 
entry(
    index = 27,
    label = "F2COCF <=> CF2O+CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.43E+12,'1/s'), n=0.46, Ea=(30062.73,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is F2COCF <=> CF2O+CF""",
)
 
entry(
    index = 28,
    label = "CF3CO <=> CF3+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78E+12,'1/s'), n=0.79, Ea=(11561.09,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CO <=> CF3+CO""",
)
 
entry(
    index = 29,
    label = "CF3CFO <=> CF2CFO+F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78E+17,'1/s'), n=-0.39, Ea=(117839.46,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CFO <=> CF2CFO+F""",
)
 
entry(
    index = 30,
    label = "CF3CFO <=> CF3+CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.79E+23,'1/s'), n=-1.88, Ea=(91230.44,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CFO <=> CF3+CFO""",
)
 
entry(
    index = 31,
    label = "CF3CFO <=> CF4+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.68E+09,'1/s'), n=1.26, Ea=(90122.89,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CFO <=> CF4+CO""",
)
 
entry(
    index = 32,
    label = "CF3CFO+H2O <=> CF3C(O)OH+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.57E-02,'cm^3/(mol*s)'), n=3.6, Ea=(30432.07,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CFO+H2O <=> CF3C(O)OH+HF""",
)
 
entry(
    index = 33,
    label = "C2F5O <=> CF3+CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.19E+12,'1/s'), n=0.21, Ea=(7626.53,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5O <=> CF3+CF2O""",
)
 
entry(
    index = 34,
    label = "C2F5OH <=> CF3+CF2OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86E+24,'1/s'), n=-2.04, Ea=(98006.27,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OH <=> CF3+CF2OH""",
)
 
entry(
    index = 35,
    label = "C2F5OH <=> CF3CFO+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.88E-08,'1/s'), n=5.97, Ea=(34454.13,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OH <=> CF3CFO+HF""",
)
 
entry(
    index = 36,
    label = "CF(O)CO <=> CFO+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.81E+12,'1/s'), n=0.39, Ea=(10740.60,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF(O)CO <=> CFO+CO""",
)
 
entry(
    index = 37,
    label = "C2F5OO <=> CF3CF2+O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.08E+21,'1/s'), n=-1.64, Ea=(65799.87,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OO <=> CF3CF2+O2""",
)
 
entry(
    index = 38,
    label = "C2F5OO <=> CF3CFO+OF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.43E+12,'1/s'), n=0.48, Ea=(94172.65,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OO <=> CF3CFO+OF""",
)
 
entry(
    index = 39,
    label = "c_F2COC(O) <=> CF2O+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.58E+12,'1/s'), n=0.3, Ea=(9852.72,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is c_F2COC(O) <=> CF2O+CO""",
)
 
entry(
    index = 40,
    label = "c_F2COC(O) <=> CF2+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.17E+13,'1/s'), n=0.33, Ea=(19504.55,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is c_F2COC(O) <=> CF2+CO2""",
)
 
entry(
    index = 41,
    label = "CF2C(O)OH <=> CF2H+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.85E-12,'1/s'), n=6.85, Ea=(32530.53,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF2C(O)OH <=> CF2H+CO2""",
)
 
entry(
    index = 42,
    label = "CF3C(O)OH <=> CF3+C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.39E+24,'1/s'), n=-2.26, Ea=(91093.88,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3C(O)OH <=> CF3+C(O)OH""",
)
 
entry(
    index = 43,
    label = "CF3C(O)OH <=> CF3OH+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.57E+09,'1/s'), n=1.23, Ea=(106083.11,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3C(O)OH <=> CF3OH+CO""",
)
 
entry(
    index = 44,
    label = "CF3C(O)OH <=> CF3H+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.19E-45,'1/s'), n=17.11, Ea=(41536.32,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3C(O)OH <=> CF3H+CO2""",
)
 
entry(
    index = 45,
    label = "CF3C(O)OH <=> c_F2COC(O)+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.57E+11,'1/s'), n=0.34, Ea=(53059.32,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3C(O)OH <=> c_F2COC(O)+HF""",
)
 
entry(
    index = 46,
    label = "CF(O)CF2OO <=> CF2CFO+O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.03E+21,'1/s'), n=-1.6, Ea=(59501.27,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF(O)CF2OO <=> CF2CFO+O2""",
)
 
entry(
    index = 47,
    label = "CF(O)CF2OO <=> CF3OO+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.32E+10,'1/s'), n=0.63, Ea=(67139.26,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF(O)CF2OO <=> CF3OO+CO""",
)
 
entry(
    index = 48,
    label = "C2F5CF <=> CF3CFCF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.78E+09,'1/s'), n=0.81, Ea=(50398.36,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CF <=> CF3CFCF2""",
)
 
entry(
    index = 49,
    label = "C2F5CF <=> CF3+CF2CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.47E+23,'1/s'), n=-2.0, Ea=(59867.53,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CF <=> CF3+CF2CF""",
)
 
entry(
    index = 50,
    label = "C2F5CF <=> CF3CF2+CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.66E+20,'1/s'), n=-1.26, Ea=(66713.17,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CF <=> CF3CF2+CF""",
)
 
entry(
    index = 51,
    label = "C2F5CF2 <=> CF2CF2+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.33E+11,'1/s'), n=0.95, Ea=(46364.64,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CF2 <=> CF2CF2+CF3""",
)
 
entry(
    index = 52,
    label = "C2F5CF2H <=> C2F5CF2+H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.67E+13,'1/s'), n=0.61, Ea=(102676.85,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CF2H <=> C2F5CF2+H""",
)
 
entry(
    index = 53,
    label = "C2F5CF2H <=> CF3CF2+CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.35E+23,'1/s'), n=-1.92, Ea=(93296.21,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CF2H <=> CF3CF2+CF2H""",
)
 
entry(
    index = 54,
    label = "C2F5CF2H <=> CF3+CF2CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.00E+24,'1/s'), n=-2.11, Ea=(95383.89,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CF2H <=> CF3+CF2CF2H""",
)
 
entry(
    index = 55,
    label = "C2F5CF2H <=> F+C2F4CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.19E+17,'1/s'), n=-0.52, Ea=(124543.13,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CF2H <=> F+C2F4CF2H""",
)
 
entry(
    index = 56,
    label = "C2F5CF2H <=> CF3CFCF2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.52E-42,'1/s'), n=15.75, Ea=(55659.29,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CF2H <=> CF3CFCF2+HF""",
)
 
entry(
    index = 57,
    label = "C3F8 <=> CF3CF2+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.21E+25,'1/s'), n=-2.03, Ea=(94408.08,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F8 <=> CF3CF2+CF3""",
)
 
entry(
    index = 58,
    label = "C3F8 <=> C2F5CF2+F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.16E+17,'1/s'), n=-0.43, Ea=(124180.97,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F8 <=> C2F5CF2+F""",
)
 
entry(
    index = 59,
    label = "C3F8 <=> CF2CF2+CF4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.80E+10,'1/s'), n=1.49, Ea=(137246.21,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F8 <=> CF2CF2+CF4""",
)
 
entry(
    index = 60,
    label = "C3F8 <=> C2F6+CF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.18E+10,'1/s'), n=1.21, Ea=(115318.91,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F8 <=> C2F6+CF2""",
)
 
entry(
    index = 61,
    label = "C3F8+H <=> C2F5CF2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.65E+03,'cm^3/(mol*s)'), n=3.12, Ea=(35260.63,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F8+H <=> C2F5CF2+HF""",
)
 
entry(
    index = 62,
    label = "C3F8+H2O <=> C3F7OH+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.77E-02,'cm^3/(mol*s)'), n=3.77, Ea=(79908.11,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F8+H2O <=> C3F7OH+HF""",
)
 
entry(
    index = 63,
    label = "C2F5CO <=> CF3CF2+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.45E+11,'1/s'), n=0.58, Ea=(9168.48,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CO <=> CF3CF2+CO""",
)
 
entry(
    index = 64,
    label = "C2F5CFO <=> CF3CF2+CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.93E+22,'1/s'), n=-1.68, Ea=(88047.83,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CFO <=> CF3CF2+CFO""",
)
 
entry(
    index = 65,
    label = "C2F5CFO <=> CF3+CF2CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.54E+23,'1/s'), n=-1.79, Ea=(88036.98,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CFO <=> CF3+CF2CFO""",
)
 
entry(
    index = 66,
    label = "C2F5CFO <=> C2F6+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.09E+09,'1/s'), n=1.4, Ea=(86945.8,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CFO <=> C2F6+CO""",
)
 
entry(
    index = 67,
    label = "C2F5CFO <=> CF2CF2+CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.87E+08,'1/s'), n=1.21, Ea=(82079.93,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CFO <=> CF2CF2+CF2O""",
)
 
entry(
    index = 68,
    label = "C2F5CFO <=> CF3OCFCF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.89E+07,'1/s'), n=1.5, Ea=(116143.54,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CFO <=> CF3OCFCF2""",
)
 
entry(
    index = 69,
    label = "C2F5CFO+H2O <=> C2F5C(O)OH+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.23E-03,'cm^3/(mol*s)'), n=3.71, Ea=(30829.36,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5CFO+H2O <=> C2F5C(O)OH+HF""",
)
 
entry(
    index = 70,
    label = "CF3OCFCF2 <=> CF3+CF2CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.66E+24,'1/s'), n=-2.13, Ea=(59169.35,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFCF2 <=> CF3+CF2CFO""",
)
 
entry(
    index = 71,
    label = "CF3OCFCF2 <=> CF3O+CF2CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.96E+23,'1/s'), n=-2.01, Ea=(112564.92,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFCF2 <=> CF3O+CF2CF""",
)
 
entry(
    index = 72,
    label = "CF3OCFCF2 <=> CF2O+CF2CF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.70E+09,'1/s'), n=1.16, Ea=(83135.26,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFCF2 <=> CF2O+CF2CF2""",
)
 
entry(
    index = 73,
    label = "CF3OCCF3 <=> CF3OCFCF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.91E+09,'1/s'), n=0.87, Ea=(41067.78,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCCF3 <=> CF3OCFCF2""",
)
 
entry(
    index = 74,
    label = "CF3OCCF3 <=> CF3CF+CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.43E+08,'1/s'), n=1.22, Ea=(48702.28,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCCF3 <=> CF3CF+CF2O""",
)
 
entry(
    index = 75,
    label = "C3F7O <=> CF3CF2+CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.92E+12,'1/s'), n=0.27, Ea=(5852.35,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7O <=> CF3CF2+CF2O""",
)
 
entry(
    index = 76,
    label = "CF3OCFCF3 <=> CF3+CF3CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.03E+11,'1/s'), n=0.65, Ea=(26570.25,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFCF3 <=> CF3+CF3CFO""",
)
 
entry(
    index = 77,
    label = "C3F7OH <=> CF3CF2+CF2OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51E+23,'1/s'), n=-1.78, Ea=(93426.09,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OH <=> CF3CF2+CF2OH""",
)
 
entry(
    index = 78,
    label = "C3F7OH <=> CF3+C2F4OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.29E+23,'1/s'), n=-1.78, Ea=(94310.36,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OH <=> CF3+C2F4OH""",
)
 
entry(
    index = 79,
    label = "C3F7OH <=> C2F5CFO+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.99E-08,'1/s'), n=6.03, Ea=(33888.86,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OH <=> C2F5CFO+HF""",
)
 
entry(
    index = 80,
    label = "CF3OCFHCF3 <=> CF3+CF3CFHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.69E+23,'1/s'), n=-2.0, Ea=(102396.15,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFHCF3 <=> CF3+CF3CFHO""",
)
 
entry(
    index = 81,
    label = "CF3OCFHCF3 <=> CF3OCFH+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.87E+24,'1/s'), n=-2.1, Ea=(97369.72,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFHCF3 <=> CF3OCFH+CF3""",
)
 
entry(
    index = 82,
    label = "CF3OCFHCF3 <=> CF3O+CF3CFH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.51E+23,'1/s'), n=-1.81, Ea=(101745.7,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFHCF3 <=> CF3O+CF3CFH""",
)
 
entry(
    index = 83,
    label = "CF3OCFHCF3 <=> CF3OCFCF2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.21E-20,'1/s'), n=9.74, Ea=(66242.71,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFHCF3 <=> CF3OCFCF2+HF""",
)
 
entry(
    index = 84,
    label = "CF3OCFHCF3 <=> CF2O+CF3CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.59E+11,'1/s'), n=0.77, Ea=(82880.02,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFHCF3 <=> CF2O+CF3CF2H""",
)
 
entry(
    index = 85,
    label = "CF(O)CF2CO <=> CF2CFO+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.18E+11,'1/s'), n=0.56, Ea=(5496.44,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF(O)CF2CO <=> CF2CFO+CO""",
)
 
entry(
    index = 86,
    label = "CF3-c_FCOC(O) <=> CF3CFO+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.29E+12,'1/s'), n=0.31, Ea=(15935.42,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3-c_FCOC(O) <=> CF3CFO+CO""",
)
 
entry(
    index = 87,
    label = "CF3-c_FCOC(O) <=> CF2CF2+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.39E+12,'1/s'), n=0.63, Ea=(32152.82,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3-c_FCOC(O) <=> CF2CF2+CO2""",
)
 
entry(
    index = 88,
    label = "CF3-c_FCOC(O) <=> CF3CF+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.81E+12,'1/s'), n=0.64, Ea=(32162.89,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3-c_FCOC(O) <=> CF3CF+CO2""",
)
 
entry(
    index = 89,
    label = "CF(O)CF2CFO <=> CF2CFOCFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.50E+06,'1/s'), n=1.38, Ea=(77809.6,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF(O)CF2CFO <=> CF2CFOCFO""",
)
 
entry(
    index = 90,
    label = "CF(O)CF2CFO <=> CF2CFO+CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.01E+21,'1/s'), n=-1.53, Ea=(81204.14,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF(O)CF2CFO <=> CF2CFO+CFO""",
)
 
entry(
    index = 91,
    label = "CF(O)CF2CFO <=> CF3CFO+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.59E+08,'1/s'), n=1.55, Ea=(87970.28,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF(O)CF2CFO <=> CF3CFO+CO""",
)
 
entry(
    index = 92,
    label = "CF2CFOCFO <=> CF2CFO+CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.57E+25,'1/s'), n=-2.52, Ea=(56793.8,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF2CFOCFO <=> CF2CFO+CFO""",
)
 
entry(
    index = 93,
    label = "CF2CFOCFO <=> CF2CF2+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.41E+10,'1/s'), n=0.54, Ea=(73549.44,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF2CFOCFO <=> CF2CF2+CO2""",
)
 
entry(
    index = 94,
    label = "CF3CFC(O)OH <=> CF3CFH+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.54E-21,'1/s'), n=9.6, Ea=(27803.89,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3CFC(O)OH <=> CF3CFH+CO2""",
)
 
entry(
    index = 95,
    label = "C2F4C(O)OH <=> CF2CF2+C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.93E+09,'1/s'), n=1.03, Ea=(39998.52,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F4C(O)OH <=> CF2CF2+C(O)OH""",
)
 
entry(
    index = 96,
    label = "C2F4C(O)OH <=> CF2CF2H+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.63E+01,'1/s'), n=2.87, Ea=(24236.77,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F4C(O)OH <=> CF2CF2H+CO2""",
)
 
entry(
    index = 97,
    label = "C2F5C(O)OH <=> CF3CF2+C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.61E+24,'1/s'), n=-2.0, Ea=(88017.66,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5C(O)OH <=> CF3CF2+C(O)OH""",
)
 
entry(
    index = 98,
    label = "C2F5C(O)OH <=> CF3+CF2C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.54E+24,'1/s'), n=-2.1, Ea=(90470.13,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5C(O)OH <=> CF3+CF2C(O)OH""",
)
 
entry(
    index = 99,
    label = "C2F5C(O)OH <=> C2F5OH+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.18E+10,'1/s'), n=1.11, Ea=(103334.92,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5C(O)OH <=> C2F5OH+CO""",
)
 
entry(
    index = 100,
    label = "C2F5C(O)OH <=> CF3CF2H+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.54E-42,'1/s'), n=16.02, Ea=(42280.65,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5C(O)OH <=> CF3CF2H+CO2""",
)
 
entry(
    index = 101,
    label = "C2F5C(O)OH <=> CF3-c_FCOC(O)+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.44E+11,'1/s'), n=0.83, Ea=(67256.37,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5C(O)OH <=> CF3-c_FCOC(O)+HF""",
)
 
entry(
    index = 102,
    label = "CF3OC(O)CF3 <=> CF3+CF3OC(O)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.40E+25,'1/s'), n=-2.35, Ea=(89361.85,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OC(O)CF3 <=> CF3+CF3OC(O)""",
)
 
entry(
    index = 103,
    label = "CF3OC(O)CF3 <=> CF3O+CF3CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.96E+24,'1/s'), n=-2.17, Ea=(102065.38,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OC(O)CF3 <=> CF3O+CF3CO""",
)
 
entry(
    index = 104,
    label = "CF3OC(O)CF3 <=> CF2O+CF3CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.87E+11,'1/s'), n=0.42, Ea=(49974.68,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OC(O)CF3 <=> CF2O+CF3CFO""",
)
 
entry(
    index = 105,
    label = "C3F7OO <=> C2F5CF2+O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.31E+19,'1/s'), n=-1.31, Ea=(64218.65,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OO <=> C2F5CF2+O2""",
)
 
entry(
    index = 106,
    label = "C3F7OO <=> C2F5CFO+OF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.30E+11,'1/s'), n=0.67, Ea=(92427.4,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OO <=> C2F5CFO+OF""",
)
 
entry(
    index = 107,
    label = "CF3OCFC(O)OH <=> CF3+CF(O)C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.03E+09,'1/s'), n=1.02, Ea=(27425.93,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFC(O)OH <=> CF3+CF(O)C(O)OH""",
)
 
entry(
    index = 108,
    label = "CF3OCFC(O)OH <=> CF2O+CF2C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.02E+07,'1/s'), n=1.62, Ea=(30984.27,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFC(O)OH <=> CF2O+CF2C(O)OH""",
)
 
entry(
    index = 109,
    label = "CF3OCFC(O)OH <=> CF3OCFH+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.146607e-12,'1/s'), n=7.1, Ea=(32688.4,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCFC(O)OH <=> CF3OCFH+CO2""",
)
 
entry(
    index = 110,
    label = "C3F7CF2 <=> CF2CF2+CF3CF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.27E+09,'1/s'), n=1.02, Ea=(41399.15,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CF2 <=> CF2CF2+CF3CF2""",
)
 
entry(
    index = 111,
    label = "C3F7CF2H <=> C2F5CF2+CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.01E+22,'1/s'), n=-1.73, Ea=(91468.17,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CF2H <=> C2F5CF2+CF2H""",
)
 
entry(
    index = 112,
    label = "C3F7CF2H <=> CF3CF2+CF2CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.02E+23,'1/s'), n=-1.92, Ea=(90402.83,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CF2H <=> CF3CF2+CF2CF2H""",
)
 
entry(
    index = 113,
    label = "C3F7CF2H <=> CF3+C2F4CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.74E+23,'1/s'), n=-1.92, Ea=(92942.19,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CF2H <=> CF3+C2F4CF2H""",
)
 
entry(
    index = 114,
    label = "C3F7CF2H <=> C2F5CFCF2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.00E-44,'1/s'), n=16.27, Ea=(53683.05,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CF2H <=> C2F5CFCF2+HF""",
)
 
entry(
    index = 115,
    label = "C4F10 <=> C3F7CF2+F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.58E+16,'1/s'), n=-0.24, Ea=(123786.17,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F10 <=> C3F7CF2+F""",
)
 
entry(
    index = 116,
    label = "C4F10 <=> C2F5CFCF3+F",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.50E+16,'1/s'), n=-0.25, Ea=(115076.6,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F10 <=> C2F5CFCF3+F""",
)
 
entry(
    index = 117,
    label = "C4F10 <=> C2F5CF2+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.06E+23,'1/s'), n=-1.84, Ea=(92772.25,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F10 <=> C2F5CF2+CF3""",
)
 
entry(
    index = 118,
    label = "C4F10 <=> CF3CF2+CF3CF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.80E+23,'1/s'), n=-1.84, Ea=(89619.23,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F10 <=> CF3CF2+CF3CF2""",
)
 
entry(
    index = 119,
    label = "C4F10 <=> CF3CF+C2F6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.27E+08,'1/s'), n=1.39, Ea=(117727.48,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F10 <=> CF3CF+C2F6""",
)
 
entry(
    index = 120,
    label = "C4F10+H <=> C3F7CF2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.29E+05,'cm^3/(mol*s)'), n=2.12, Ea=(35197.26,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F10+H <=> C3F7CF2+HF""",
)
 
entry(
    index = 121,
    label = "C3F7CO <=> C2F5CF2+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.85E+11,'1/s'), n=0.68, Ea=(8179.35,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CO <=> C2F5CF2+CO""",
)
 
entry(
    index = 122,
    label = "C3F7CFO <=> C2F5CF2+CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.41E+21,'1/s'), n=-1.45, Ea=(86577.52,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CFO <=> C2F5CF2+CFO""",
)
 
entry(
    index = 123,
    label = "C3F7CFO <=> CF3CF2+CF2CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.42E+22,'1/s'), n=-1.56, Ea=(83413.64,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CFO <=> CF3CF2+CF2CFO""",
)
 
entry(
    index = 124,
    label = "C3F7CFO <=> CF3+C2F4CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.09E+22,'1/s'), n=-1.56, Ea=(93214.39,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CFO <=> CF3+C2F4CFO""",
)
 
entry(
    index = 125,
    label = "C3F7CFO <=> C3F8+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.93E+08,'1/s'), n=1.43, Ea=(86880.44,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CFO <=> C3F8+CO""",
)
 
entry(
    index = 126,
    label = "C3F7CFO <=> CF3CFCF2+CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.46E+06,'1/s'), n=1.56, Ea=(80832.97,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CFO <=> CF3CFCF2+CF2O""",
)
 
entry(
    index = 127,
    label = "C3F7CFO+H2O <=> C3F7C(O)OH+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.67E-03,'cm^3/(mol*s)'), n=3.86, Ea=(31139.62,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7CFO+H2O <=> C3F7C(O)OH+HF""",
)
 
entry(
    index = 128,
    label = "C2F5OCFCF2 <=> CF3+CF2OCFCF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.69E+24,'1/s'), n=-2.24, Ea=(97357.87,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFCF2 <=> CF3+CF2OCFCF2""",
)
 
entry(
    index = 129,
    label = "C2F5OCFCF2 <=> CF3CF2+CF2CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.17E+24,'1/s'), n=-2.17, Ea=(55469.83,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFCF2 <=> CF3CF2+CF2CFO""",
)
 
entry(
    index = 130,
    label = "C2F5OCFCF2 <=> C2F5O+CF2CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.33E+23,'1/s'), n=-1.99, Ea=(111006.78,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFCF2 <=> C2F5O+CF2CF""",
)
 
entry(
    index = 131,
    label = "C2F5OCFCF2 <=> CF3CFO+CF2CF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.30E+08,'1/s'), n=1.02, Ea=(81186.65,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFCF2 <=> CF3CFO+CF2CF2""",
)
 
entry(
    index = 132,
    label = "C2F5OCCF3 <=> CF2OC(CF3)CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.83E+08,'1/s'), n=0.97, Ea=(72710.03,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCCF3 <=> CF2OC(CF3)CF3""",
)
 
entry(
    index = 133,
    label = "C2F5OCCF3 <=> C2F5OCFCF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.83E+09,'1/s'), n=0.88, Ea=(40777.28,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCCF3 <=> C2F5OCFCF2""",
)
 
entry(
    index = 134,
    label = "C2F5OCCF3 <=> CF3CFO+CF3CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.53E+09,'1/s'), n=0.9, Ea=(52188.21,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCCF3 <=> CF3CFO+CF3CF""",
)
 
entry(
    index = 135,
    label = "C4F9O <=> C2F5CF2+CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.71E+11,'1/s'), n=0.55, Ea=(5045.12,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9O <=> C2F5CF2+CF2O""",
)
 
entry(
    index = 136,
    label = "C2F5OCFCF3 <=> CF3CFO+CF3CF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.59E+10,'1/s'), n=0.65, Ea=(22327.43,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFCF3 <=> CF3CFO+CF3CF2""",
)
 
entry(
    index = 137,
    label = "C4F9OH <=> C2F5CF2+CF2OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.66E+22,'1/s'), n=-1.67, Ea=(91684.99,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9OH <=> C2F5CF2+CF2OH""",
)
 
entry(
    index = 138,
    label = "C4F9OH <=> CF3CF2+C2F4OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.60E+22,'1/s'), n=-1.66, Ea=(89416.25,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9OH <=> CF3CF2+C2F4OH""",
)
 
entry(
    index = 139,
    label = "C4F9OH <=> CF3+C3F6OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.16E+22,'1/s'), n=-1.67, Ea=(92160.67,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9OH <=> CF3+C3F6OH""",
)
 
entry(
    index = 140,
    label = "C4F9OH <=> C3F7CFO+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.17E-07,'1/s'), n=5.9, Ea=(33573.23,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9OH <=> C3F7CFO+HF""",
)
 
entry(
    index = 141,
    label = "C2F5OCFHCF3 <=> CF3+CF2OCFHCF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.29E+25,'1/s'), n=-2.47, Ea=(97424.47,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFHCF3 <=> CF3+CF2OCFHCF3""",
)
 
entry(
    index = 142,
    label = "C2F5OCFHCF3 <=> C2F5OCFH+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.69E+24,'1/s'), n=-2.22, Ea=(97230.56,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFHCF3 <=> C2F5OCFH+CF3""",
)
 
entry(
    index = 143,
    label = "C2F5OCFHCF3 <=> CF3CF2+CF3CFHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.76E+23,'1/s'), n=-2.12, Ea=(99031.96,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFHCF3 <=> CF3CF2+CF3CFHO""",
)
 
entry(
    index = 144,
    label = "C2F5OCFHCF3 <=> C2F5O+CF3CFH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.63E+23,'1/s'), n=-1.87, Ea=(100522.87,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFHCF3 <=> C2F5O+CF3CFH""",
)
 
entry(
    index = 145,
    label = "C2F5OCFHCF3 <=> C2F5OCFCF2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.87E-20,'1/s'), n=9.7, Ea=(66385.89,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFHCF3 <=> C2F5OCFCF2+HF""",
)
 
entry(
    index = 146,
    label = "C2F5OCFHCF3 <=> CF3CFO+CF3CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.98E+09,'1/s'), n=0.79, Ea=(79773.96,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFHCF3 <=> CF3CFO+CF3CF2H""",
)
 
entry(
    index = 147,
    label = "CF(O)CF2CF2CFO <=> C2F4CFO+CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.61E+20,'1/s'), n=-1.3, Ea=(86978.28,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF(O)CF2CF2CFO <=> C2F4CFO+CFO""",
)
 
entry(
    index = 148,
    label = "CF(O)CF2CF2CFO <=> CF2CFO+CF2CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.49E+21,'1/s'), n=-1.4, Ea=(77266.68,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF(O)CF2CF2CFO <=> CF2CFO+CF2CFO""",
)
 
entry(
    index = 149,
    label = "CF(O)CF2CF2CFO <=> C2F5CFO+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.19E+06,'1/s'), n=2.07, Ea=(82365.79,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF(O)CF2CF2CFO <=> C2F5CFO+CO""",
)
 
entry(
    index = 150,
    label = "CF2CFOCF2CFO <=> CF2OCFCF2+CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.11E+21,'1/s'), n=-1.72, Ea=(89384.1,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF2CFOCF2CFO <=> CF2OCFCF2+CFO""",
)
 
entry(
    index = 151,
    label = "CF2CFOCF2CFO <=> CF2CFO+CF2CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.20E+22,'1/s'), n=-1.76, Ea=(47485.2,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF2CFOCF2CFO <=> CF2CFO+CF2CFO""",
)
 
entry(
    index = 152,
    label = "CF2CFOCF2CFO <=> CF3OCFCF2+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.94E+05,'1/s'), n=2.13, Ea=(84929.46,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF2CFOCF2CFO <=> CF3OCFCF2+CO""",
)
 
entry(
    index = 153,
    label = "C2F5-c_FCOC(O) <=> C2F5CFO+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.74E+12,'1/s'), n=0.27, Ea=(15958.37,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5-c_FCOC(O) <=> C2F5CFO+CO""",
)
 
entry(
    index = 154,
    label = "C2F5-c_FCOC(O) <=> CF3CFCF2+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.27E+12,'1/s'), n=0.64, Ea=(32427.8,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5-c_FCOC(O) <=> CF3CFCF2+CO2""",
)
 
entry(
    index = 155,
    label = "C2F5-c_FCOC(O) <=> C2F5CF+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.90E+08,'1/s'), n=1.39, Ea=(64235.65,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5-c_FCOC(O) <=> C2F5CF+CO2""",
)
 
entry(
    index = 156,
    label = "C3F6C(O)OH <=> CF2CF2+CF2C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.78E+07,'1/s'), n=1.48, Ea=(37548.51,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F6C(O)OH <=> CF2CF2+CF2C(O)OH""",
)
 
entry(
    index = 157,
    label = "C3F6C(O)OH <=> C2F4CF2H+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.44E-44,'1/s'), n=16.52, Ea=(41072.79,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F6C(O)OH <=> C2F4CF2H+CO2""",
)
 
entry(
    index = 158,
    label = "C3F7C(O)OH <=> C2F5CF2+C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.50E+23,'1/s'), n=-1.85, Ea=(86653.66,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7C(O)OH <=> C2F5CF2+C(O)OH""",
)
 
entry(
    index = 159,
    label = "C3F7C(O)OH <=> CF3CF2+CF2C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.18E+24,'1/s'), n=-1.94, Ea=(85953.12,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7C(O)OH <=> CF3CF2+CF2C(O)OH""",
)
 
entry(
    index = 160,
    label = "C3F7C(O)OH <=> CF3+C2F4C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.87E+24,'1/s'), n=-1.99, Ea=(94064.97,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7C(O)OH <=> CF3+C2F4C(O)OH""",
)
 
entry(
    index = 161,
    label = "C3F7C(O)OH <=> C3F7OH+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.36E+08,'1/s'), n=1.49, Ea=(102989.19,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7C(O)OH <=> C3F7OH+CO""",
)
 
entry(
    index = 162,
    label = "C3F7C(O)OH <=> C2F5CF2H+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.18E-40,'1/s'), n=15.66, Ea=(42257.3,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7C(O)OH <=> C2F5CF2H+CO2""",
)
 
entry(
    index = 163,
    label = "C3F7C(O)OH <=> C2F5-c_FCOC(O)+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.06E+10,'1/s'), n=0.85, Ea=(55739.56,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7C(O)OH <=> C2F5-c_FCOC(O)+HF""",
)
 
entry(
    index = 164,
    label = "C2F5OC(O)CF3 <=> CF3+C2F5OC(O)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.61E+24,'1/s'), n=-2.42, Ea=(88881.4,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OC(O)CF3 <=> CF3+C2F5OC(O)""",
)
 
entry(
    index = 165,
    label = "C2F5OC(O)CF3 <=> CF3+CF2OC(O)CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.89E+25,'1/s'), n=-2.56, Ea=(96716.74,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OC(O)CF3 <=> CF3+CF2OC(O)CF3""",
)
 
entry(
    index = 166,
    label = "C2F5OC(O)CF3 <=> C2F5O+CF3CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78E+24,'1/s'), n=-2.18, Ea=(100406.39,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OC(O)CF3 <=> C2F5O+CF3CO""",
)
 
entry(
    index = 167,
    label = "C2F5OC(O)CF3 <=> CF3CFO+CF3CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.16E+12,'1/s'), n=-0.04, Ea=(50928.36,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OC(O)CF3 <=> CF3CFO+CF3CFO""",
)
 
entry(
    index = 168,
    label = "C2F5OC(O)CF3 <=> C2F5OCF3+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.97E+10,'1/s'), n=0.75, Ea=(92443.65,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OC(O)CF3 <=> C2F5OCF3+CO""",
)
 
entry(
    index = 169,
    label = "CF3OC(CF3)OCF3 <=> CF3OC(O)CF3+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.59E+07,'1/s'), n=1.64, Ea=(23421.24,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OC(CF3)OCF3 <=> CF3OC(O)CF3+CF3""",
)
 
entry(
    index = 170,
    label = "CF3OC(CF3)OCF3 <=> CF3OCFCF3+CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.48E+03,'1/s'), n=2.51, Ea=(65844.16,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OC(CF3)OCF3 <=> CF3OCFCF3+CF2O""",
)
 
entry(
    index = 171,
    label = "CF3OC(CF3)OCO <=> CF3OC(O)CF3+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.11E+11,'1/s'), n=0.35, Ea=(17594.48,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OC(CF3)OCO <=> CF3OC(O)CF3+CO""",
)
 
entry(
    index = 172,
    label = "CF3OC(CF3)OCO <=> CF3OCCF3+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.62E+11,'1/s'), n=0.59, Ea=(24008.33,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OC(CF3)OCO <=> CF3OCCF3+CO2""",
)
 
entry(
    index = 173,
    label = "C2F5OCFC(O)OH <=> CF3CF2+CF(O)C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.21E+08,'1/s'), n=0.88, Ea=(23310.13,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFC(O)OH <=> CF3CF2+CF(O)C(O)OH""",
)
 
entry(
    index = 174,
    label = "C2F5OCFC(O)OH <=> CF3CFO+CF2C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.85E+07,'1/s'), n=1.44, Ea=(23859.65,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFC(O)OH <=> CF3CFO+CF2C(O)OH""",
)
 
entry(
    index = 175,
    label = "C2F5OCFC(O)OH <=> C2F5OCFH+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.10E-13,'1/s'), n=7.32, Ea=(32895.38,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCFC(O)OH <=> C2F5OCFH+CO2""",
)
 
entry(
    index = 176,
    label = "CF3OCF(CF3)C(O)OH <=> CF3OCFCF3+C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.23E+25,'1/s'), n=-2.09, Ea=(86406.46,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCF(CF3)C(O)OH <=> CF3OCFCF3+C(O)OH""",
)
 
entry(
    index = 177,
    label = "CF3OCF(CF3)C(O)OH <=> CF3OCFC(O)OH+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.18E+26,'1/s'), n=-2.2, Ea=(88258.26,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCF(CF3)C(O)OH <=> CF3OCFC(O)OH+CF3""",
)
 
entry(
    index = 178,
    label = "CF3OCF(CF3)C(O)OH <=> CF3+CF3CFOC(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.39E+24,'1/s'), n=-1.94, Ea=(101346.44,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCF(CF3)C(O)OH <=> CF3+CF3CFOC(O)OH""",
)
 
entry(
    index = 179,
    label = "CF3OCF(CF3)C(O)OH <=> CF3O+CF3CFC(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.66E+25,'1/s'), n=-2.08, Ea=(92732.9,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCF(CF3)C(O)OH <=> CF3O+CF3CFC(O)OH""",
)
 
entry(
    index = 180,
    label = "CF3OCF(CF3)C(O)OH <=> CF3OCFHCF3+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.99E-30,'1/s'), n=12.69, Ea=(46973.63,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCF(CF3)C(O)OH <=> CF3OCFHCF3+CO2""",
)
 
entry(
    index = 181,
    label = "CF3OCF(CF3)C(O)OH <=> CF2O+C2F5C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.94E+10,'1/s'), n=0.98, Ea=(81914.87,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCF(CF3)C(O)OH <=> CF2O+C2F5C(O)OH""",
)
 
entry(
    index = 182,
    label = "CF3OCF(CF3)C(O)OH <=> CF3OC(CF3)OCO+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.80E+12,'1/s'), n=0.42, Ea=(48368.07,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF3OCF(CF3)C(O)OH <=> CF3OC(CF3)OCO+HF""",
)
 
entry(
    index = 183,
    label = "C3F7OCFCF2 <=> CF3+C2F4OCFCF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.03E+23,'1/s'), n=-2.1, Ea=(94143.94,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFCF2 <=> CF3+C2F4OCFCF2""",
)
 
entry(
    index = 184,
    label = "C3F7OCFCF2 <=> CF3CF2+CF2OCFCF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.39E+23,'1/s'), n=-2.11, Ea=(93175.61,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFCF2 <=> CF3CF2+CF2OCFCF2""",
)
 
entry(
    index = 185,
    label = "C3F7OCFCF2 <=> C2F5CF2+CF2CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.25E+23,'1/s'), n=-2.04, Ea=(54440.59,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFCF2 <=> C2F5CF2+CF2CFO""",
)
 
entry(
    index = 186,
    label = "C3F7OCFCF2 <=> C3F7O+CF2CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.19E+22,'1/s'), n=-1.86, Ea=(110777.34,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFCF2 <=> C3F7O+CF2CF""",
)
 
entry(
    index = 187,
    label = "C3F7OCFCF2 <=> C2F5CFO+CF2CF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.54E+08,'1/s'), n=1.06, Ea=(80760.28,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFCF2 <=> C2F5CFO+CF2CF2""",
)
 
entry(
    index = 188,
    label = "C3F7OCCF3 <=> CF2OC(CF3)C2F5",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.02E+05,'1/s'), n=1.52, Ea=(74068.27,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCCF3 <=> CF2OC(CF3)C2F5""",
)
 
entry(
    index = 189,
    label = "C3F7OCCF3 <=> C3F7OCFCF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.16E+07,'1/s'), n=1.56, Ea=(40037.15,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCCF3 <=> C3F7OCFCF2""",
)
 
entry(
    index = 190,
    label = "C3F7OCCF3 <=> C2F5CFO+CF3CF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.26E+08,'1/s'), n=1.07, Ea=(51125.81,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCCF3 <=> C2F5CFO+CF3CF""",
)
 
entry(
    index = 191,
    label = "C3F7OCFCF3 <=> C2F5CF2+CF3CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.62E+09,'1/s'), n=0.75, Ea=(21448.48,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFCF3 <=> C2F5CF2+CF3CFO""",
)
 
entry(
    index = 192,
    label = "C3F7OCFHCF3 <=> CF3+C2F4OCFHCF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.64E+23,'1/s'), n=-2.21, Ea=(94232.17,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFHCF3 <=> CF3+C2F4OCFHCF3""",
)
 
entry(
    index = 193,
    label = "C3F7OCFHCF3 <=> C3F7OCFH+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.95E+23,'1/s'), n=-1.98, Ea=(97110.85,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFHCF3 <=> C3F7OCFH+CF3""",
)
 
entry(
    index = 194,
    label = "C3F7OCFHCF3 <=> CF3CF2+CF2OCFHCF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.47E+24,'1/s'), n=-2.23, Ea=(93133.74,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFHCF3 <=> CF3CF2+CF2OCFHCF3""",
)
 
entry(
    index = 195,
    label = "C3F7OCFHCF3 <=> C2F5CF2+CF3CFHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.58E+22,'1/s'), n=-1.88, Ea=(97794.26,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFHCF3 <=> C2F5CF2+CF3CFHO""",
)
 
entry(
    index = 196,
    label = "C3F7OCFHCF3 <=> C3F7O+CF3CFH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.38E+21,'1/s'), n=-1.63, Ea=(99984.99,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFHCF3 <=> C3F7O+CF3CFH""",
)
 
entry(
    index = 197,
    label = "C3F7OCFHCF3 <=> C3F7OCFCF2+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.76E-20,'1/s'), n=9.71, Ea=(66524.53,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFHCF3 <=> C3F7OCFCF2+HF""",
)
 
entry(
    index = 198,
    label = "C3F7OCFHCF3 <=> C2F5CFO+CF3CF2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.18E+10,'1/s'), n=0.8, Ea=(79374.87,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFHCF3 <=> C2F5CFO+CF3CF2H""",
)
 
entry(
    index = 199,
    label = "C3F7-c_FCOC(O) <=> C3F7CFO+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.67E+12,'1/s'), n=0.24, Ea=(16106.5,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7-c_FCOC(O) <=> C3F7CFO+CO""",
)
 
entry(
    index = 200,
    label = "C3F7-c_FCOC(O) <=> C3F7CF+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.89E+13,'1/s'), n=0.18, Ea=(32595.14,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7-c_FCOC(O) <=> C3F7CF+CO2""",
)
 
entry(
    index = 201,
    label = "C4F9C(O)OH <=> CF3+C3F6C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.29E+22,'1/s'), n=-1.56, Ea=(92402.49,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9C(O)OH <=> CF3+C3F6C(O)OH""",
)
 
entry(
    index = 202,
    label = "C4F9C(O)OH <=> CF3CF2+C2F4C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.56E+22,'1/s'), n=-1.56, Ea=(88931.24,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9C(O)OH <=> CF3CF2+C2F4C(O)OH""",
)
 
entry(
    index = 203,
    label = "C4F9C(O)OH <=> C2F5CF2+CF2C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.60E+22,'1/s'), n=-1.52, Ea=(83972.42,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9C(O)OH <=> C2F5CF2+CF2C(O)OH""",
)
 
entry(
    index = 204,
    label = "C4F9C(O)OH <=> C3F7CF2+C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.98E+22,'1/s'), n=-1.41, Ea=(86113.97,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9C(O)OH <=> C3F7CF2+C(O)OH""",
)
 
entry(
    index = 205,
    label = "C4F9C(O)OH <=> C3F7-c_FCOC(O)+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.32E+07,'1/s'), n=1.61, Ea=(55284.04,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9C(O)OH <=> C3F7-c_FCOC(O)+HF""",
)
 
entry(
    index = 206,
    label = "C4F9C(O)OH <=> C3F7CF2H+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.93E-43,'1/s'), n=16.39, Ea=(41420.36,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C4F9C(O)OH <=> C3F7CF2H+CO2""",
)
 
entry(
    index = 207,
    label = "C3F7OC(O)CF3 <=> CF3+C3F7OC(O)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.29E+23,'1/s'), n=-2.17, Ea=(88723.33,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OC(O)CF3 <=> CF3+C3F7OC(O)""",
)
 
entry(
    index = 208,
    label = "C3F7OC(O)CF3 <=> CF3+C2F4OC(O)CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.72E+24,'1/s'), n=-2.29, Ea=(94058.54,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OC(O)CF3 <=> CF3+C2F4OC(O)CF3""",
)
 
entry(
    index = 209,
    label = "C3F7OC(O)CF3 <=> CF3CF2+CF2OC(O)CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.04E+24,'1/s'), n=-2.31, Ea=(92177.21,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OC(O)CF3 <=> CF3CF2+CF2OC(O)CF3""",
)
 
entry(
    index = 210,
    label = "C3F7OC(O)CF3 <=> C3F7O+CF3CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.06E+22,'1/s'), n=-1.92, Ea=(99819.7,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OC(O)CF3 <=> C3F7O+CF3CO""",
)
 
entry(
    index = 211,
    label = "C3F7OC(O)CF3 <=> C2F5CFO+CF3CFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.47E+11,'1/s'), n=0.12, Ea=(50136.69,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OC(O)CF3 <=> C2F5CFO+CF3CFO""",
)
 
entry(
    index = 212,
    label = "C3F7OC(O)CF3 <=> C3F7OCF3+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.44E+11,'1/s'), n=0.67, Ea=(94390.82,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OC(O)CF3 <=> C3F7OCF3+CO""",
)
 
entry(
    index = 213,
    label = "C2F5OC(CF3)OCF3 <=> C2F5OC(O)CF3+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.20E+07,'1/s'), n=1.51, Ea=(23274.37,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OC(CF3)OCF3 <=> C2F5OC(O)CF3+CF3""",
)
 
entry(
    index = 214,
    label = "C2F5OC(CF3)OCF3 <=> C2F5OCFCF3+CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.52E+04,'1/s'), n=2.17, Ea=(66752.6,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OC(CF3)OCF3 <=> C2F5OCFCF3+CF2O""",
)
 
entry(
    index = 215,
    label = "C2F5OC(CF3)OCO <=> C2F5OC(O)CF3+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51E+11,'1/s'), n=0.39, Ea=(17285.46,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OC(CF3)OCO <=> C2F5OC(O)CF3+CO""",
)
 
entry(
    index = 216,
    label = "C2F5OC(CF3)OCO <=> C2F5OCCF3+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.01E+13,'1/s'), n=0.17, Ea=(24869.35,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OC(CF3)OCO <=> C2F5OCCF3+CO2""",
)
 
entry(
    index = 217,
    label = "C3F7OCFC(O)OH <=> C2F5CF2+CF(O)C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.96E+09,'1/s'), n=0.66, Ea=(22657.32,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFC(O)OH <=> C2F5CF2+CF(O)C(O)OH""",
)
 
entry(
    index = 218,
    label = "C3F7OCFC(O)OH <=> C2F5CFO+CF2C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.00E+06,'1/s'), n=1.39, Ea=(21512.21,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCFC(O)OH <=> C2F5CFO+CF2C(O)OH""",
)
 
entry(
    index = 219,
    label = "C2F5OCF(CF3)C(O)OH <=> C2F5OCFCF3+C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.26E+27,'1/s'), n=-3.05, Ea=(86516.14,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCF(CF3)C(O)OH <=> C2F5OCFCF3+C(O)OH""",
)
 
entry(
    index = 220,
    label = "C2F5OCF(CF3)C(O)OH <=> C2F5OCFC(O)OH+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.51E+28,'1/s'), n=-3.16, Ea=(88261.41,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCF(CF3)C(O)OH <=> C2F5OCFC(O)OH+CF3""",
)
 
entry(
    index = 221,
    label = "C2F5OCF(CF3)C(O)OH <=> CF3+CF2OCF(CF3)C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.87E+27,'1/s'), n=-3.21, Ea=(97239.13,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCF(CF3)C(O)OH <=> CF3+CF2OCF(CF3)C(O)OH""",
)
 
entry(
    index = 222,
    label = "C2F5OCF(CF3)C(O)OH <=> CF3CF2+CF3CFOC(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.30E+26,'1/s'), n=-2.9, Ea=(98101.07,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCF(CF3)C(O)OH <=> CF3CF2+CF3CFOC(O)OH""",
)
 
entry(
    index = 223,
    label = "C2F5OCF(CF3)C(O)OH <=> C2F5O+CF3CFC(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.57E+27,'1/s'), n=-2.97, Ea=(91728.9,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCF(CF3)C(O)OH <=> C2F5O+CF3CFC(O)OH""",
)
 
entry(
    index = 224,
    label = "C2F5OCF(CF3)C(O)OH <=> C2F5OCFHCF3+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.77E-25,'1/s'), n=11.12, Ea=(47765.57,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCF(CF3)C(O)OH <=> C2F5OCFHCF3+CO2""",
)
 
entry(
    index = 225,
    label = "C2F5OCF(CF3)C(O)OH <=> CF3CFO+C2F5C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.36E+10,'1/s'), n=0.57, Ea=(77873.21,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCF(CF3)C(O)OH <=> CF3CFO+C2F5C(O)OH""",
)
 
entry(
    index = 226,
    label = "C2F5OCF(CF3)C(O)OH <=> C2F5OC(CF3)OCO+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.51E+14,'1/s'), n=-0.2, Ea=(56198.89,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C2F5OCF(CF3)C(O)OH <=> C2F5OC(CF3)OCO+HF""",
)
 
entry(
    index = 227,
    label = "C3F7OC(CF3)OCO <=> C3F7OC(O)CF3+CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.46E+11,'1/s'), n=0.45, Ea=(17288.75,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OC(CF3)OCO <=> C3F7OC(O)CF3+CO""",
)
 
entry(
    index = 228,
    label = "C3F7OC(CF3)OCO <=> C3F7OCCF3+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.73E+13,'1/s'), n=-0.01, Ea=(25134.51,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OC(CF3)OCO <=> C3F7OCCF3+CO2""",
)
 
entry(
    index = 229,
    label = "C3F7OCF(CF3)C(O)OH <=> C3F7OCFCF3+C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.75E+27,'1/s'), n=-3.2, Ea=(86426.88,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCF(CF3)C(O)OH <=> C3F7OCFCF3+C(O)OH""",
)
 
entry(
    index = 230,
    label = "C3F7OCF(CF3)C(O)OH <=> CF3+C2F4OCF(CF3)C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.09E+27,'1/s'), n=-3.34, Ea=(94502.63,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCF(CF3)C(O)OH <=> CF3+C2F4OCF(CF3)C(O)OH""",
)
 
entry(
    index = 231,
    label = "C3F7OCF(CF3)C(O)OH <=> C3F7OCFC(O)OH+CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.03E+28,'1/s'), n=-3.32, Ea=(87974.5,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCF(CF3)C(O)OH <=> C3F7OCFC(O)OH+CF3""",
)
 
entry(
    index = 232,
    label = "C3F7OCF(CF3)C(O)OH <=> CF3CF2+CF2OCF(CF3)C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.48E+28,'1/s'), n=-3.36, Ea=(92858.72,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCF(CF3)C(O)OH <=> CF3CF2+CF2OCF(CF3)C(O)OH""",
)
 
entry(
    index = 233,
    label = "C3F7OCF(CF3)C(O)OH <=> C2F5CF2+CF3CFOC(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.25E+26,'1/s'), n=-3.05, Ea=(96873.68,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCF(CF3)C(O)OH <=> C2F5CF2+CF3CFOC(O)OH""",
)
 
entry(
    index = 234,
    label = "C3F7OCF(CF3)C(O)OH <=> C3F7O+CF3CFC(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.34E+27,'1/s'), n=-3.12, Ea=(91201.33,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCF(CF3)C(O)OH <=> C3F7O+CF3CFC(O)OH""",
)
 
entry(
    index = 235,
    label = "C3F7OCF(CF3)C(O)OH <=> C2F5CFO+C2F5C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.43E+11,'1/s'), n=0.16, Ea=(77189.93,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCF(CF3)C(O)OH <=> C2F5CFO+C2F5C(O)OH""",
)
 
entry(
    index = 236,
    label = "C3F7OCF(CF3)C(O)OH <=> C3F7OCFHCF3+CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.14E-22,'1/s'), n=10.39, Ea=(48295.89,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCF(CF3)C(O)OH <=> C3F7OCFHCF3+CO2""",
)
 
entry(
    index = 237,
    label = "C3F7OCF(CF3)C(O)OH <=> C3F7OC(CF3)OCO+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.78E+15,'1/s'), n=-0.84, Ea=(49834.17,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCF(CF3)C(O)OH <=> C3F7OC(CF3)OCO+HF""",
)
 
entry(
    index = 238,
    label = "C3F7OCF(CF3)C(O)OH <=> C3F8+CF3C(O)C(O)OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.08E+10,'1/s'), n=0.39, Ea=(88203.52,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F7OCF(CF3)C(O)OH <=> C3F8+CF3C(O)C(O)OH""",
)

