#!/usr/bin/env python
# encoding: utf-8

name = "Perfluorinated_Alkyl_Rearrangement/groups"
shortDesc = ""
longDesc = """
*5F                         *3C           *6F
     |                           |             | 
    *4C - *1O - *2C - *3C  <=>  *4C- - *1O+ = *2C - *5F
     |
    *6F
"""

template(reactants=["Root"], products=["rearranged"], ownReverse=False)

reverse = "Perfluorinated_Alkyl_Rearrangement_Reverse"
reversible = True

reactantNum = 1

productNum = 1

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*3', 1, '*2'],
    ['BREAK_BOND', '*5', 1, '*4'],
    ['BREAK_BOND', '*6', 1, '*4'],
    ['FORM_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*6', 1, '*2'],
    ['FORM_BOND', '*2', 1, '*5'],
    ['CHANGE_BOND', '*1', 1, '*2'],
    ['LOSE_PAIR', '*2', 1],
    ['LOSE_PAIR', '*1', 1],
    ['GAIN_PAIR', '*4', 1],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *4 C   u0 p0 {2,S} {4,S} {5,S}
2 *1 O   u0 p2 {1,S} {3,S}
3 *2 C   u0 p1 {2,S} {6,S}
4 *5 F1s u0 {1,S}
5 *6 F1s u0 {1,S}
6 *3 C   u0 p0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-6C-R_Ext-6C-R_Ext-7R!H-R_8R!H->C",
    group = 
"""
1 *4 C   u0 p0 r0 {2,S} {4,S} {5,S} {7,[S,D,T,B,Q]}
2 *1 O   u0 p2 r0 {1,S} {3,S}
3 *2 C   u0 p1 r0 {2,S} {6,S}
4 *5 F1s u0 {1,S}
5 *6 F1s u0 {1,S}
6 *3 C   u0 p0 r0 {3,S}
7    C   ux {1,[S,D,T,B,Q]} {8,S}
8    C   u0 r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-6C-R_Ext-6C-R_Ext-7R!H-R_N-8R!H->C",
    group = 
"""
1 *4 C   u0 p0 r0 {2,S} {4,S} {5,S} {7,[S,D,T,B,Q]}
2 *1 O   u0 p2 r0 {1,S} {3,S}
3 *2 C   u0 p1 r0 {2,S} {6,S}
4 *5 F1s u0 {1,S}
5 *6 F1s u0 {1,S}
6 *3 C   u0 p0 r0 {3,S}
7    C   ux {1,[S,D,T,B,Q]} {8,S}
8    F   u0 r0 {7,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-6C-R_Ext-6C-R_Ext-7R!H-R_8R!H->C
    L2: Root_Ext-6C-R_Ext-6C-R_Ext-7R!H-R_N-8R!H->C
"""
)

