#!/usr/bin/env python
# encoding: utf-8

name = "Perfluorinated_Alkyl_Rearrangement/groups"
shortDesc = ""
longDesc = """
 
    *5F                         *3C           *6F
     |                           |             | 
    *4C - *1O - *2C - *3C  <=>  *4C- - *1O+ = *2C - *5F
     |
    *6F   
"""

template(reactants=["Root"], products=['rearranged'], ownReverse=False)

reversible = True
reverse = "Perfluorinated_Alkyl_Rearrangement_Reverse"
         
reactantNum = 1

productNum = 1
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*3', 1, '*2'],
    ['BREAK_BOND', '*5', 1, '*4'],    
    ['BREAK_BOND', '*6', 1, '*4'],
    ['FORM_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*6', 1, '*2'],
    ['FORM_BOND', '*2', 1, '*5'],    
    ['CHANGE_BOND', '*1', 1, '*2'],
    ['LOSE_PAIR', '*2', 1],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 O u0 p2 {2,S} {4,S}
2 *2 C u0 p1 {1,S} {3,S}
3 *3 C u0 p0 {2,S}
4 *4 C u0 p0 {1,S} {5,S} {6,S}
5 *5 F1s u0 {4,S}
6 *6 F1s u0 {4,S}
""",
    kinetics = None,
)

