#!/usr/bin/env python
# encoding: utf-8

name = "CF_Radical_Formation_3/groups"
shortDesc = ""
longDesc = """
*1F - *2C. - *4O  <=>     *4O = *3C    +     *2C. - *1F 
        |   / 
      *3C
"""

template(reactants=["Root"], products=["O=C-R", "CF"], ownReverse=False)

reverse = "CF_addition_to_perfluorinated_carbonyl"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*2', 1, '*4'],
    ['BREAK_BOND', '*3', 1, '*2'],
    ['GAIN_PAIR', '*2', 1],
    ['CHANGE_BOND', '*4', 1, '*3'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 C   u1       {2,S} {3,S} {4,S}
2 *3 C   u[0,1,2] {1,S} {3,S}
3 *4 O   u0       {1,S} {2,S}
4 *1 F1s u0       {1,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
"""
)

