#!/usr/bin/env python
# encoding: utf-8

name = "1,3_Insertion_CO2/groups"
shortDesc = ""
longDesc = """

"""

template(reactants=["Root"], products=["R_(CS2)_R'"], ownReverse=False)

reverse = "1,2_Elimination_CO2"
reversible = True

reactantNum = 2

productNum = 1

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*3', 1, '*4'],
    ['CHANGE_BOND', '*1', -1, '*2'],
    ['FORM_BOND', '*1', 1, '*3'],
    ['FORM_BOND', '*2', 1, '*4'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 R         u0 {5,S}
5 *4 R         u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_5R->C",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 R         u0 {5,S}
5 *4 C         u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_5R->C_4R->C",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 C         u0 {5,S}
5 *4 C         u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_5R->C_N-4R->C",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 [F,H]     u0 {5,S}
5 *4 C         u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_N-5R->C",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 R         u0 {5,S}
5 *4 H         u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_N-5R->C_4R->F",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 F         u0 {5,S}
5 *4 H         u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_N-5R->C_N-4R->F",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 [C,H]     u0 {5,S}
5 *4 H         u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_N-5R->C_N-4R->F_4CH->C",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 C         u0 {5,S}
5 *4 H         u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 C         u0 {5,S} {6,[S,D,T,B,Q]}
5 *4 H         u0 {4,S}
6    R!H       ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_6R!H-u1",
    group = 
"""
1 *1 Cdd       u0 r0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 C         u0 r0 {5,S} {6,S}
5 *4 H         u0 r0 {4,S}
6    R!H       u1 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1",
    group = 
"""
1 *1 Cdd       u0       {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       {5,S} {6,[S,D,T,B,Q]}
5 *4 H         u0       {4,S}
6    R!H       u[0,2,3] {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C",
    group = 
"""
1 *1 Cdd       u0       {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       {5,S} {6,[S,D,T,B,Q]}
5 *4 H         u0       {4,S}
6    C         u[0,2,3] {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R",
    group = 
"""
1 *1 Cdd       u0       {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       {5,S} {6,[S,D,T,B,Q]}
5 *4 H         u0       {4,S}
6    C         u[0,2,3] {4,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
7    R!H       ux       {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_7R!H-u1",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 C         u0 {5,S} {6,[S,D,T,B,Q]}
5 *4 H         u0 {4,S}
6    C         u0 {4,[S,D,T,B,Q]} {7,S}
7    R!H       u1 r0 {6,S}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1",
    group = 
"""
1 *1 Cdd       u0       {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       {5,S} {6,S}
5 *4 H         u0       {4,S}
6    C         u[0,2,3] {4,S} {7,[S,D,T,B,Q]}
7    R!H       u0       {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_8R!H->O",
    group = 
"""
1 *1 Cdd       u0       {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       {5,S} {6,S} {8,[S,D,T,B,Q]}
5 *4 H         u0       {4,S}
6    C         u[0,2,3] {4,S} {7,[S,D,T,B,Q]}
7    F         u0       {6,[S,D,T,B,Q]}
8    O         ux       {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_8R!H->O_Ext-8O-R_Ext-9R!H-R_Ext-8O-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-8O-R_10R!H->C",
    group = 
"""
1  *1 Cdd       u0       {2,D} {3,D}
2  *2 [O2d,S2d] u0       {1,D}
3     [O2d,S2d] u0       {1,D}
4  *3 C         u0       {5,S} {6,S} {8,[S,D,T,B,Q]}
5  *4 H         u0       {4,S}
6     C         u[0,2,3] {4,S} {7,[S,D,T,B,Q]}
7     F         u0       {6,[S,D,T,B,Q]}
8     O         ux       {4,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
9     C         ux       {8,[S,D,T,B,Q]} {10,S}
10    C         u0       {9,S}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_8R!H->O_Ext-8O-R_Ext-9R!H-R_Ext-8O-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-8O-R_10R!H->C_Ext-10C-R_11R!H->C",
    group = 
"""
1  *1 Cdd       u0       r0 {2,D} {3,D}
2  *2 [O2d,S2d] u0       {1,D}
3     [O2d,S2d] u0       {1,D}
4  *3 C         u0       r0 {5,S} {6,S} {8,[S,D,T,B,Q]}
5  *4 H         u0       r0 {4,S}
6     C         u[0,2,3] r0 {4,S} {7,[S,D,T,B,Q]}
7     F         u0       {6,[S,D,T,B,Q]}
8     O         ux       {4,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
9     C         ux       {8,[S,D,T,B,Q]} {10,S}
10    C         u0       r0 {9,S} {11,S}
11    C         u0       r0 {10,S}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_8R!H->O_Ext-8O-R_Ext-9R!H-R_Ext-8O-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-8O-R_10R!H->C_Ext-10C-R_N-11R!H->C",
    group = 
"""
1  *1 Cdd       u0       r0 {2,D} {3,D}
2  *2 [O2d,S2d] u0       {1,D}
3     [O2d,S2d] u0       {1,D}
4  *3 C         u0       r0 {5,S} {6,S} {8,[S,D,T,B,Q]}
5  *4 H         u0       r0 {4,S}
6     C         u[0,2,3] r0 {4,S} {7,[S,D,T,B,Q]}
7     F         u0       {6,[S,D,T,B,Q]}
8     O         ux       {4,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
9     C         ux       {8,[S,D,T,B,Q]} {10,S}
10    C         u0       r0 {9,S} {11,S}
11    F         u0       r0 {10,S}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_8R!H->O_Ext-8O-R_Ext-9R!H-R_Ext-8O-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-8O-R_N-10R!H->C",
    group = 
"""
1  *1 Cdd       u0       r0 {2,D} {3,D}
2  *2 [O2d,S2d] u0       {1,D}
3     [O2d,S2d] u0       {1,D}
4  *3 C         u0       r0 {5,S} {6,S} {8,[S,D,T,B,Q]}
5  *4 H         u0       r0 {4,S}
6     C         u[0,2,3] r0 {4,S} {7,[S,D,T,B,Q]}
7     F         u0       {6,[S,D,T,B,Q]}
8     O         ux       {4,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
9     C         ux       {8,[S,D,T,B,Q]} {10,S}
10    F         u0       r0 {9,S}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_N-8R!H->O",
    group = 
"""
1 *1 Cdd       u0       {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       {5,S} {6,S} {8,[S,D,T,B,Q]}
5 *4 H         u0       {4,S}
6    C         u[0,2,3] {4,S} {7,[S,D,T,B,Q]}
7    R!H       u0       {6,[S,D,T,B,Q]}
8    F         ux       {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_N-8R!H->O_7R!H->C",
    group = 
"""
1 *1 Cdd       u0       {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       {5,S} {6,S} {8,[S,D,T,B,Q]}
5 *4 H         u0       {4,S}
6    C         u[0,2,3] {4,S} {7,[S,D,T,B,Q]}
7    C         u0       {6,[S,D,T,B,Q]}
8    F         ux       {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_N-8R!H->O_7R!H->C_Ext-7C-R_9R!H->C",
    group = 
"""
1 *1 Cdd       u0       r0 {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       r0 {5,S} {6,S} {8,[S,D,T,B,Q]}
5 *4 H         u0       r0 {4,S}
6    C         u[0,2,3] r0 {4,S} {7,[S,D,T,B,Q]}
7    C         u0       {6,[S,D,T,B,Q]} {9,S}
8    F         ux       {4,[S,D,T,B,Q]}
9    C         u0       r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_N-8R!H->O_7R!H->C_Ext-7C-R_N-9R!H->C",
    group = 
"""
1 *1 Cdd       u0       r0 {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       r0 {5,S} {6,S} {8,[S,D,T,B,Q]}
5 *4 H         u0       r0 {4,S}
6    C         u[0,2,3] r0 {4,S} {7,[S,D,T,B,Q]}
7    C         u0       {6,[S,D,T,B,Q]} {9,S}
8    F         ux       {4,[S,D,T,B,Q]}
9    F         u0       r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_N-8R!H->O_N-7R!H->C",
    group = 
"""
1 *1 Cdd       u0       r0 {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       r0 {5,S} {6,S} {8,[S,D,T,B,Q]}
5 *4 H         u0       r0 {4,S}
6    C         u[0,2,3] r0 {4,S} {7,[S,D,T,B,Q]}
7    F         u0       {6,[S,D,T,B,Q]}
8    F         ux       {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-4C-R",
    group = 
"""
1 *1 Cdd       u0       {2,D} {3,D}
2 *2 [O2d,S2d] u0       {1,D}
3    [O2d,S2d] u0       {1,D}
4 *3 C         u0       {5,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
5 *4 H         u0       {4,S}
6    C         u[0,2,3] {4,[S,D,T,B,Q]}
7    R!H       ux       {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_N-6R!H->C",
    group = 
"""
1 *1 Cdd       u0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 C         u0 {5,S} {6,[S,D,T,B,Q]}
5 *4 H         u0 {4,S}
6    [O,F]     u0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_N-5R->C_N-4R->F_N-4CH->C",
    group = 
"""
1 *1 Cdd       u0 r0 {2,D} {3,D}
2 *2 [O2d,S2d] u0 {1,D}
3    [O2d,S2d] u0 {1,D}
4 *3 H         u0 r0 {5,S}
5 *4 H         u0 r0 {4,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_5R->C
        L3: Root_5R->C_4R->C
        L3: Root_5R->C_N-4R->C
    L2: Root_N-5R->C
        L3: Root_N-5R->C_4R->F
        L3: Root_N-5R->C_N-4R->F
            L4: Root_N-5R->C_N-4R->F_4CH->C
                L5: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R
                    L6: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_6R!H-u1
                    L6: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1
                        L7: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C
                            L8: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R
                                L9: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_7R!H-u1
                                L9: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1
                                    L10: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_8R!H->O
                                        L11: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_8R!H->O_Ext-8O-R_Ext-9R!H-R_Ext-8O-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-8O-R_10R!H->C
                                            L12: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_8R!H->O_Ext-8O-R_Ext-9R!H-R_Ext-8O-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-8O-R_10R!H->C_Ext-10C-R_11R!H->C
                                            L12: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_8R!H->O_Ext-8O-R_Ext-9R!H-R_Ext-8O-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-8O-R_10R!H->C_Ext-10C-R_N-11R!H->C
                                        L11: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_8R!H->O_Ext-8O-R_Ext-9R!H-R_Ext-8O-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-10R!H-R_Ext-8O-R_Ext-8O-R_N-10R!H->C
                                    L10: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_N-8R!H->O
                                        L11: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_N-8R!H->O_7R!H->C
                                            L12: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_N-8R!H->O_7R!H->C_Ext-7C-R_9R!H->C
                                            L12: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_N-8R!H->O_7R!H->C_Ext-7C-R_N-9R!H->C
                                        L11: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-6C-R_N-7R!H-u1_Ext-6C-R_Ext-6C-R_N-8R!H->O_N-7R!H->C
                            L8: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_6R!H->C_Ext-4C-R
                        L7: Root_N-5R->C_N-4R->F_4CH->C_Ext-4C-R_N-6R!H-u1_N-6R!H->C
            L4: Root_N-5R->C_N-4R->F_N-4CH->C
"""
)

forbidden(
    label = "carbonyl_sulfide_O2d",
    group = 
"""
1 *1 Cdd u0 {2,D} {5,D}
2 *2 O2d u0 {1,D}
3 *3 R   u0 {4,D}
4 *4 R   u0 {3,D}
5    S2d u0 {1,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "carbonyl_sulfide_S2d",
    group = 
"""
1 *1 Cdd u0 {2,D} {5,D}
2 *2 S2d u0 {1,D}
3 *3 R   u0 {4,D}
4 *4 R   u0 {3,D}
5    O2d u0 {1,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

