#!/usr/bin/env python
# encoding: utf-8

name = "1,3_sigmatropic_rearrangement_PFAS"

autoGenerated=False

entry(
    index = 0,
    label = "C2F5CFO <=> CF3OCFCF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.89E+07,'1/s'), n=1.5, Ea=(116143.54,'cal/mol'), T0=(1,'K')))

entry(
    index = 1,
    label = "CF(O)CF2CFO <=> CF2CFOCFO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.50E+06,'1/s'), n=1.38, Ea=(77809.6,'cal/mol'), T0=(1,'K')))

entry(
    index = 2,
    label = "C2F5OCCF3 <=> CF2OC(CF3)CF3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.83E+08,'1/s'), n=0.97, Ea=(72710.03,'cal/mol'), T0=(1,'K')))

entry(
    index = 3,
    label = "C3F7OCCF3 <=> CF2OC(CF3)C2F5",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.02E+05,'1/s'), n=1.52, Ea=(74068.27,'cal/mol'), T0=(1,'K')))

entry(
    index = 4,
    label = "C2H5CHO <=> CH3OCHCH2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.26E+07,'1/s'), n=1.81, Ea=(92397.34,'cal/mol'), T0=(1,'K')))

entry(
    index = 5,
    label = "CH(O)CH2CHO <=> CH2CHOCHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.15E+06,'1/s'), n=1.45, Ea=(48596.75,'cal/mol'), T0=(1,'K')))

entry(
    index = 6,
    label = "CH(O)CH2CH2CHO <=> CH2CHOCH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.60E+08,'1/s'), n=0.98, Ea=(87754.81,'cal/mol'), T0=(1,'K')))

entry(
    index = 7,
    label = "C2H5OCCH3 <=> CH2OC(CH3)CH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.97E+08,'1/s'), n=1.04, Ea=(64427.0,'cal/mol'), T0=(1,'K')))

entry(
    index = 8,
    label = "C3H7OCCH3 <=> CH2OC(CH3)C2H5",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.03E+09,'1/s'), n=0.6, Ea=(26107.26,'cal/mol'), T0=(1,'K')))



