#!/usr/bin/env python
# encoding: utf-8

name = "PFAS_HPL_Test"

autoGenerated=False

entry(
    index = 0,
    label = "CF2H <=> CF+HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.01E+12,'1/s'), n=0.49, Ea=(72977.06,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is CF2H <=> CF+HF""",
)
