#!/usr/bin/env python
# encoding: utf-8

name = "Perfluoroalkene_Formation/groups"
shortDesc = ""
longDesc = """
R          *3F             R
     |           |              |
F - *1C - *2C - *4C   <=>  F - *1C - *3F    +  *2C = *4C
"""

template(reactants=["Root"], products=["RCF2", "perfluoroalkene"], ownReverse=False)

reverse = "reverse_of_perfluoroalkene_formation"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['CHANGE_BOND', '*2', 1, '*4'],
    ['FORM_BOND', '*1', 1, '*3'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 C   u[0,1]     {2,S} {4,S} {5,[S,D]}
2 *2 C   u[0,1,2]   {1,S} {3,[S,D]}
3 *4 C   u[0,1,2]   {2,[S,D]} {6,S}
4    F1s u0         {1,S}
5    R   u[0,1,2,3] {1,[S,D]}
6 *3 F1s u0         {3,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-1C-R",
    group = 
"""
1 *1 C   u0 r0 {2,S} {4,S} {5,[S,D]} {7,[S,D,T,B,Q]}
2 *2 C   u0 r0 {1,S} {3,S}
3 *4 C   u0 r0 {2,S} {6,S}
4    F1s u0 r0 {1,S}
5    R   u0 r0 {1,[S,D]}
6 *3 F1s u0 r0 {3,S}
7    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-3C-R_7R!H->C",
    group = 
"""
1 *1 C   u0 r0 {2,S} {4,S} {5,[S,D]}
2 *2 C   u0 r0 {1,S} {3,S}
3 *4 C   u0 r0 {2,S} {6,S} {7,S}
4    F1s u0 r0 {1,S}
5    O   u0 r0 {1,[S,D]}
6 *3 F1s u0 r0 {3,S}
7    C   u0 r0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_Ext-3C-R_N-7R!H->C",
    group = 
"""
1 *1 C   u0 r0 {2,S} {4,S} {5,[S,D]}
2 *2 C   u0 r0 {1,S} {3,S}
3 *4 C   u0 r0 {2,S} {6,S} {7,S}
4    F1s u0 r0 {1,S}
5    O   u0 r0 {1,[S,D]}
6 *3 F1s u0 r0 {3,S}
7    F   u0 r0 {3,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-1C-R
    L2: Root_Ext-3C-R_7R!H->C
    L2: Root_Ext-3C-R_N-7R!H->C
"""
)

