#!/usr/bin/env python
# encoding: utf-8

name = "Perfluoroalkene_Formation/groups"
shortDesc = ""
longDesc = """

     R          *3F             R
     |           |              |
F - *1C - *2C - *4C   <=>  F - *1C - *3F    +  *2C = *4C

"""

template(reactants=["Root"], products=["RCF2", "perfluoroalkene"], ownReverse=False)

reversible = True
reverse = "reverse_of_perfluoroalkene_formation"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['CHANGE_BOND', '*2', 1, '*4'],
    ['FORM_BOND', '*1', 1, '*3'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 C u[0,1] {5,S} {6,[S,D]} {2,S}
2 *2 C u[0,1,2] {1,S} {4,[S,D]}
3 *3 F1s u0 {4,S}
4 *4 C u[0,1,2] {3,S} {2,[S,D]}
5 F1s u0 {1,S}
6 R u[0,1,2,3] {1,[S,D]}
""",
    kinetics = None,
)
