#!/usr/bin/env python
# encoding: utf-8

name = "CombFlame2017/45-Olm"
shortDesc = "/Users/rwest/Code/RMG-importer/RMG-models/CombFlame2017/45-Olm/olm_mech.txt"
longDesc = """
Carsten Olm, Tam?s Varga, ?va Valk?, Henry J. Curran, Tam?s Tur?nyi,
Uncertainty quantification of a newly optimized methanol and formaldehyde combustion mechanism,
Combustion and Flame,
Volume 186,
2017,
Pages 45-64,
ISSN 0010-2180,
https://doi.org/10.1016/j.combustflame.2017.07.029.
(http://www.sciencedirect.com/science/article/pii/S0010218017302742)
Abstract: A detailed reaction mechanism for methanol combustion that is capable of describing ignition, flame propagation and species concentration profiles with high accuracy has been developed. Starting from a modified version of the methanol combustion mechanism of Li et al. (2007) and adopting the H2/CO base chemistry from the joint optimized hydrogen and syngas combustion mechanism of Varga et al. (2016), an optimization of 57 Arrhenius parameters of 17 important elementary reactions was performed, using several thousand indirect measurement data points, as well as direct and theoretical determinations of reaction rate coefficients as optimization targets. The final optimized mechanism was compared to 18 reaction mechanisms published in recent years, with respect to their accuracy in reproducing the available indirect experimental data for methanol and formaldehyde combustion. The utilized indirect measurement data, in total 24,900 data points in 265 datasets, include measurements of ignition delay times, laminar burning velocities and species profiles captured using a variety of experimental techniques. In addition to new best fit values for all rate parameters, the covariance matrix of the optimized parameters, which provides a quantitative description of the temperature-dependent ranges of uncertainty for the optimized rate coefficients, was calculated. These posterior uncertainty limits are much narrower than the prior limits in the temperature range for which experimental data are available. The uncertainty of the self-reaction of H?2 radicals and important H-atom abstraction reactions from the methanol molecule are discussed in detail.
Keywords: Methanol combustion; Formaldehyde combustion; Chemical kinetic mechanisms; Mechanism optimization; Parameter uncertainty

Note: the following reaction was commented out
OHEX<=>OH+HV                        1.4500E+06    0.0000       0.000

OHEX was removed entirely.
This will surely mess up the "optimized" chemistry.
But not sure what else to do while this branch of RMG 
cannot store molecular term symbols and thus cannot distinguish
between OH and excited OH.
"""
autoGenerated=False
entry(
    index = 0,
    label = "H + O2 <=> O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.0712e+15,'cm^3/(mol*s)'), n=-0.48596, Ea=(67481.1,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H + O2 <=> O + OH""",
)

entry(
    index = 1,
    label = "O + H2 <=> H + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2554e+06,'cm^3/(mol*s)'), n=2.27039, Ea=(29110.6,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is O + H2 <=> H + OH""",
)

entry(
    index = 2,
    label = "OH + H2 <=> H + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.3193e+07,'cm^3/(mol*s)'), n=1.87803, Ea=(13185.1,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is OH + H2 <=> H + H2O""",
)

entry(
    index = 3,
    label = "OH + OH <=> O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(84999,'cm^3/(mol*s)'), n=2.26419, Ea=(-7468.31,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is OH + OH <=> O + H2O""",
)

entry(
    index = 4,
    label = "H + H <=> H2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(4.9806e+18,'cm^6/(mol^2*s)'), n=-1.21273, Ea=(2561.02,'J/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 12.0, 'O=C=O': 3.8, '[Ar]': 1.0, '[C-]#[O+]': 1.9, '[H][H]': 2.5, '[He]': 0.83, '[O][O]': 1.0}),
    shortDesc = """The chemkin file reaction is H + H <=> H2""",
)

entry(
    index = 5,
    label = "O + O <=> O2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(6.165e+15,'cm^6/(mol^2*s)'), n=-0.5, Ea=(0,'J/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 12.0, 'O=C=O': 3.8, '[Ar]': 0.83, '[C-]#[O+]': 1.9, '[H][H]': 2.5, '[He]': 0.83}),
    shortDesc = """The chemkin file reaction is O + O <=> O2""",
)

entry(
    index = 6,
    label = "O + H <=> OH",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(4.714e+18,'cm^6/(mol^2*s)'), n=-1, Ea=(0,'J/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 12.0, 'O=C=O': 2.0, '[Ar]': 0.75, '[C-]#[O+]': 1.5, '[H][H]': 2.5, '[He]': 0.75, '[O][O]': 1.0}),
    shortDesc = """The chemkin file reaction is O + H <=> OH""",
)

entry(
    index = 7,
    label = "H + OH <=> H2O",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1.4818e+24,'cm^6/(mol^2*s)'), n=-2.53792, Ea=(505.42,'J/mol'), T0=(1,'K')), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 12.0, 'O=C=O': 3.8, '[Ar]': 0.38, '[C-]#[O+]': 1.9, '[H][H]': 2.5, '[He]': 0.44, '[O][O]': 1.0}),
    shortDesc = """The chemkin file reaction is H + OH <=> H2O""",
)

entry(
    index = 8,
    label = "H + O2 <=> HO2",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(4.65e+12,'cm^3/(mol*s)'), n=0.44, Ea=(0,'J/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(5.2669e+19,'cm^6/(mol^2*s)'), n=-1.37367, Ea=(0,'J/mol'), T0=(1,'K')), alpha=0.67, T3=(1e-30,'K'), T1=(1e+30,'K'), T2=(1e+30,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 11.372, 'O=C=O': 3.8, '[Ar]': 0.474, '[C-]#[O+]': 1.9, '[H][H]': 1.511, '[He]': 0.65, '[O][O]': 1.0}),
    shortDesc = """The chemkin file reaction is H + O2 <=> HO2""",
)

entry(
    index = 9,
    label = "H + HO2 <=> H2 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.1231e+06,'cm^3/(mol*s)'), n=2.1133, Ea=(-6798.58,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H + HO2 <=> H2 + O2""",
)

entry(
    index = 10,
    label = "HO2 + H <=> OH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.7734e+13,'cm^3/(mol*s)'), n=0, Ea=(715.627,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + H <=> OH + OH""",
)

entry(
    index = 11,
    label = "HO2 + O <=> OH + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.25e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + O <=> OH + O2""",
)

entry(
    index = 12,
    label = "HO2 + OH <=> H2O + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.584e+11,'cm^3/(mol*s)'), n=0.42008, Ea=(-3969.33,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + OH <=> H2O + O2""",
)

entry(
    index = 13,
    label = "HO2 + HO2 <=> H2O2 + O2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(1.2135e+10,'cm^3/(mol*s)'), n=0.422484, Ea=(-6194.53,'J/mol'), T0=(1,'K')), Arrhenius(A=(1.6883e+16,'cm^3/(mol*s)'), n=-0.681126, Ea=(54106.2,'J/mol'), T0=(1,'K'))]),
    shortDesc = """The chemkin file reaction is HO2 + HO2 <=> H2O2 + O2""",
)

entry(
    index = 14,
    label = "OH + OH <=> H2O2",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(214800,'cm^3/(mol*s)'), n=2.3219, Ea=(-14237,'J/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.9928e+18,'cm^6/(mol^2*s)'), n=-1.17797, Ea=(-17878.7,'J/mol'), T0=(1,'K')), alpha=0.43, T3=(1e-30,'K'), T1=(1e+30,'K'), T2=(1e+30,'K'), efficiencies={'O': 5.0, 'O=C=O': 1.07, 'OO': 5.13, '[Ar]': 0.67, '[C-]#[O+]': 1.87, '[H][H]': 2.47, '[He]': 0.43, '[O][O]': 0.8}),
    shortDesc = """The chemkin file reaction is OH + OH <=> H2O2""",
)

entry(
    index = 15,
    label = "H2O2 + H <=> H2O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.41e+13,'cm^3/(mol*s)'), n=0, Ea=(16612.2,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2O2 + H <=> H2O + OH""",
)

entry(
    index = 16,
    label = "H2O2 + H <=> H2 + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.7543e+19,'cm^3/(mol*s)'), n=-1.92495, Ea=(39438.9,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2O2 + H <=> H2 + HO2""",
)

entry(
    index = 17,
    label = "H2O2 + O <=> OH + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.55e+06,'cm^3/(mol*s)'), n=2, Ea=(16612.2,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2O2 + O <=> OH + HO2""",
)

entry(
    index = 18,
    label = "H2O2 + OH <=> H2O + HO2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(1.74e+12,'cm^3/(mol*s)'), n=0, Ea=(1330.65,'J/mol'), T0=(1,'K')), Arrhenius(A=(7.59e+13,'cm^3/(mol*s)'), n=0, Ea=(30416.7,'J/mol'), T0=(1,'K'))]),
    shortDesc = """The chemkin file reaction is H2O2 + OH <=> H2O + HO2""",
)

entry(
    index = 19,
    label = "CO + O <=> CO2",
    degeneracy = 1.0,
    kinetics = Lindemann(arrheniusHigh=Arrhenius(A=(1.362e+10,'cm^3/(mol*s)'), n=0, Ea=(9975.7,'J/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.173e+24,'cm^6/(mol^2*s)'), n=-2.79, Ea=(17537,'J/mol'), T0=(1,'K')), efficiencies={'O': 12.0, 'O=C=O': 3.6, '[Ar]': 0.7, '[C-]#[O+]': 1.75, '[H][H]': 2.0, '[He]': 0.7}),
    shortDesc = """The chemkin file reaction is CO + O <=> CO2""",
)

entry(
    index = 20,
    label = "CO + O2 <=> CO2 + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.8865e+12,'cm^3/(mol*s)'), n=0, Ea=(199589,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CO + O2 <=> CO2 + O""",
)

entry(
    index = 21,
    label = "CO + OH <=> CO2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(16596,'cm^3/(mol*s)'), n=2.22171, Ea=(-5776.4,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CO + OH <=> CO2 + H""",
)

entry(
    index = 22,
    label = "CO + HO2 <=> CO2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.5144e+07,'cm^3/(mol*s)'), n=1.67957, Ea=(75983.5,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CO + HO2 <=> CO2 + OH""",
)

entry(
    index = 23,
    label = "CH3 + CH3 <=> C2H6",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(9.214e+16,'cm^3/(mol*s)'), n=-1.17, Ea=(2660.46,'J/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.135e+36,'cm^6/(mol^2*s)'), n=-5.246, Ea=(7134.48,'J/mol'), T0=(1,'K')), alpha=0.405, T3=(1120,'K'), T1=(69.6,'K'), T2=(1e+15,'K'), efficiencies={'O': 5.0, 'O=C=O': 3.0, '[C-]#[O+]': 2.0, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH3 + CH3 <=> C2H6""",
)

entry(
    index = 24,
    label = "CH3 + H <=> CH4",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1.27e+16,'cm^3/(mol*s)'), n=-0.63, Ea=(1602.61,'J/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.477e+33,'cm^6/(mol^2*s)'), n=-4.76, Ea=(10210.2,'J/mol'), T0=(1,'K')), alpha=0.783, T3=(74,'K'), T1=(2941,'K'), T2=(6964,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[Ar]': 0.7, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is CH3 + H <=> CH4""",
)

entry(
    index = 25,
    label = "CH4 + H <=> CH3 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.47e+07,'cm^3/(mol*s)'), n=1.97, Ea=(46907.5,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH4 + H <=> CH3 + H2""",
)

entry(
    index = 26,
    label = "CH4 + O <=> CH3 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.15e+12,'cm^3/(mol*s)'), n=0.5, Ea=(43057.8,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH4 + O <=> CH3 + OH""",
)

entry(
    index = 27,
    label = "CH4 + OH <=> CH3 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.72e+06,'cm^3/(mol*s)'), n=1.96, Ea=(11042.7,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH4 + OH <=> CH3 + H2O""",
)

entry(
    index = 28,
    label = "CH3 + HO2 <=> CH4 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.8953e+18,'cm^3/(mol*s)'), n=-1.92309, Ea=(7384.76,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + HO2 <=> CH4 + O2""",
)

entry(
    index = 29,
    label = "CH4 + HO2 <=> CH3 + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+11,'cm^3/(mol*s)'), n=0, Ea=(77746.8,'J/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH4 + HO2 <=> CH3 + H2O2""",
)

entry(
    index = 30,
    label = "OH + CH3 <=> CH3OH",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(5.4887e+12,'cm^3/(mol*s)'), n=0.299671, Ea=(-3583.19,'J/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.0561e+54,'cm^6/(mol^2*s)'), n=-10.9202, Ea=(46652.2,'J/mol'), T0=(1,'K')), alpha=0.412, T3=(195,'K'), T1=(5900,'K'), T2=(6394,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
    shortDesc = """The chemkin file reaction is OH + CH3 <=> CH3OH""",
)

