#!/usr/bin/env python
# encoding: utf-8

name = "CO2_Elimination_From_Lactone/groups"
shortDesc = ""
longDesc = """

    R!O
     |     
F - *1C - *2C = *3O  <=>  *4O = *2C = *3O  +  R!O - *1C - F
       \  /
       *4O
"""

template(reactants=["Root"], products=["CO2", "C_F"], ownReverse=False)

reversible = True
reverse = "CO2_addition_to_perfluoroalkane"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*4', 1, '*1'],
    ['BREAK_BOND', '*2', 1, '*1'],
    ['CHANGE_BOND', '*4', 1, '*2'],
    ['GAIN_PAIR', '*1', 1]
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 C u[0,1,2] {5,S} {2,S} {4,S} {6,S}
2 *2 C u0 {1,S} {4,S} {3,D}
3 *3 O u0 {2,D}
4 *4 O u0 {1,S} {2,S}
5 F1s u0 {1,S}
6 R!O u[0,1,2,3] {1,S}
""",
    kinetics = None,
)
