#!/usr/bin/env python
# encoding: utf-8

name = "CF_Radical_Formation_1/groups"
shortDesc = ""
longDesc = """


*1F - *2C. - *4F     <=>     *1F - *3R     +     *2C. - *4F 
        |
      *3R
"""

template(reactants=["Root"], products=["F_R", "CF"], ownReverse=False)

reversible = True
reverse = "HF_perfluoroalkyl_radical_combination"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*2'],
    ['GAIN_PAIR', '*2', 1],
    ['FORM_BOND', '*1', 1, '*3'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1  *2 C u1 {2,S} {3,S} {4,S}
2  *3 H u0 {1,S}
3  *4 F1s u0 {1,S}
4  *1 F1s u0 {1,S}
""",
    kinetics = None,
)
