#!/usr/bin/env python
# encoding: utf-8

name = "CF_Radical_Formation_1/groups"
shortDesc = ""
longDesc = """
*1F - *2C. - *4F     <=>     *1F - *3R     +     *2C. - *4F 
        |
      *3R
"""

template(reactants=["Root"], products=["F_R", "CF"], ownReverse=False)

reverse = "HF_perfluoroalkyl_radical_combination"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*2'],
    ['GAIN_PAIR', '*2', 1],
    ['FORM_BOND', '*1', 1, '*3'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 C   u1 {2,S} {3,S} {4,S}
2 *3 R   u0 {1,S}
3 *4 F1s u0 {1,S}
4 *1 F1s u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_2R->C",
    group = 
"""
1 *2 C   u1 {2,S} {3,S} {4,S}
2 *3 C   u0 {1,S}
3 *4 F1s u0 {1,S}
4 *1 F1s u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_2R->C_Ext-2C-R_5R!H->O",
    group = 
"""
1 *2 C   u1 r0 {2,S} {3,S} {4,S}
2 *3 C   u0 r0 {1,S} {5,[S,D,T,B,Q]}
3 *4 F1s u0 {1,S}
4 *1 F1s u0 {1,S}
5    O   u0 r0 {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_2R->C_Ext-2C-R_N-5R!H->O",
    group = 
"""
1 *2 C   u1 r0 {2,S} {3,S} {4,S}
2 *3 C   u0 r0 {1,S} {5,S}
3 *4 F1s u0 {1,S}
4 *1 F1s u0 {1,S}
5    F   u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_N-2R->C",
    group = 
"""
1 *2 C                        u1 r0 {2,S} {3,S} {4,S}
2 *3 [N,P,F,I,Br,Cl,O,Si,H,S] u0 r0 {1,S}
3 *4 F1s                      u0 {1,S}
4 *1 F1s                      u0 {1,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_2R->C
        L3: Root_2R->C_Ext-2C-R_5R!H->O
        L3: Root_2R->C_Ext-2C-R_N-5R!H->O
    L2: Root_N-2R->C
"""
)

