#!/usr/bin/env python
# encoding: utf-8

name = "CO_Elimination_From_Lactone/groups"
shortDesc = ""
longDesc = """
C=O is elminated from an alpha-lactone. 


            *4O
            /  \           
   *1O = *2C - *3C  <=>  *1O # *2C    +     *4O = *3C


"""

template(reactants=["Root"], products=["C#O", "O=C_"], ownReverse=False)

reversible = True
reverse = "Recombination_to_Lactone"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*4', 1, '*2'],
    ['BREAK_BOND', '*2', 1, '*3'],
    ['CHANGE_BOND', '*4', 1, '*3'],
    ['CHANGE_BOND', '*1', 1, '*2'],
    ['GAIN_PAIR', '*2', '1'],
    ['LOSE_PAIR', '*1', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1  *2 C  u0 {2,D} {3,S} {4,S}
2  *1 O  u0 {1,D}
3  *4 O  u0 {1,S} {4,S}
4  *3 C  u0 {1,S} {3,S} 
""",
    kinetics = None,
)


         