#!/usr/bin/env python
# encoding: utf-8

name = "1,3_sigmatropic_rearrangement/groups"
shortDesc = ""
longDesc = """
20211127: The 1,3_sigmatropic_rearrangement family was too generalized and did a poor job of estimating ketoenol 
reactions that matched the root node. Thus, this family was broken up into two families:
1) ketoenol tautomerization reactions
2) 1,3 sigmatropic rearrangement (this file)

20211010: The ketoenol family was generalized to accept R!H rather than previously only accepting O or S.
The family name was also updated to 1,3_sigmatropic_rearrangement to reflect the newly extended reaction template.


20180202: Sulfur was added to this family and is treated the same as oxygen.
https://github.com/ReactionMechanismGenerator/RMG-database/commit/9e9d300b3a0fce1bbb9aa138b2990b264fb1e37b
Ideally we would like to branch this into a new family "R=RSR <=> RRR=S"
once relevant kinetic data is available
"""

template(reactants=["Root"], products=["Root"], ownReverse=True)

reversible = True

reverseMap = {'*1': '*3', '*3': '*1'}

reactantNum = 1

productNum = 1

autoGenerated = True

recipe(actions=[
    ['CHANGE_BOND', '*1', -1, '*2'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*4', 1, '*1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 R!H u0 {2,S} {3,D}
2 *3 R!H u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 R!H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_1R!H->C",
    group = 
"""
1 *2 C   u0 {2,S} {3,D}
2 *3 R!H u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 R!H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_1R!H->C_1C-inRing",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D}
2 *3 R!H u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 R!H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_1R!H->C_1C-inRing_2R!H->N",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D}
2 *3 N   u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 C   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_1R!H->C_1C-inRing_2R!H->N_Ext-4R!H-R_5R!H->C",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D}
2 *3 N   u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 C   u0 {2,S} {5,D}
5    C   u0 {4,D}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_1R!H->C_1C-inRing_2R!H->N_Ext-4R!H-R_5R!H->C_Ext-1C-R",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D} {6,S}
2 *3 N   u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 C   u0 {2,S} {5,D}
5    C   u0 {4,D}
6    C   u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_1R!H->C_1C-inRing_2R!H->N_Ext-4R!H-R_5R!H->C_Ext-1C-R_3R!H->N",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,D} {6,S}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 C u0 r1 {2,S} {5,D}
5    C u0 r1 {4,D}
6    C u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_1R!H->C_1C-inRing_2R!H->N_Ext-4R!H-R_5R!H->C_Ext-1C-R_N-3R!H->N",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,D} {6,S}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 r1 {2,S} {5,D}
5    C u0 r1 {4,D}
6    C u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_1R!H->C_1C-inRing_2R!H->N_Ext-4R!H-R_N-5R!H->C",
    group = 
"""
1 *2 C                      u0 r1 {2,S} {3,D}
2 *3 N                      u0 r1 {1,S} {4,S}
3 *1 R!H                    u0 {1,D}
4 *4 C                      u0 r1 {2,S} {5,D}
5    [N,P,F,I,Br,Cl,O,Si,S] u0 r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_1R!H->C_1C-inRing_N-2R!H->N",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D}
2 *3 O   u0 {1,S} {4,S}
3 *1 N   u0 {1,D}
4 *4 R!H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_1R!H->C_1C-inRing_N-2R!H->N_4R!H->N",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,D}
2 *3 O u0 r1 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 N u0 r1 {2,S}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_1R!H->C_1C-inRing_N-2R!H->N_N-4R!H->N",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 C u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_1R!H->C_1C-inRing_N-2R!H->N_N-4R!H->N_Ext-1C-R",
    group = 
"""
1 *2 C   u0 r1 {2,S} {3,D} {5,[S,D,T,B,Q]}
2 *3 O   u0 r1 {1,S} {4,S}
3 *1 N   u0 {1,D}
4 *4 C   u0 r1 {2,S}
5    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_1R!H->C_1C-inRing_N-2R!H->N_N-4R!H->N_Ext-4C-R_5R!H->C",
    group = 
"""
1 *2 C u0 r1 {2,S} {3,D}
2 *3 O u0 r1 {1,S} {4,S}
3 *1 N u0 r1 {1,D}
4 *4 C u0 r1 {2,S} {5,D}
5    C u0 r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_1R!H->C_1C-inRing_N-2R!H->N_N-4R!H->N_Ext-4C-R_N-5R!H->C",
    group = 
"""
1 *2 C                      u0 r1 {2,S} {3,D}
2 *3 O                      u0 r1 {1,S} {4,S}
3 *1 N                      u0 r1 {1,D}
4 *4 C                      u0 r1 {2,S} {5,D}
5    [N,P,F,I,Br,Cl,O,Si,S] u0 r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_1R!H->C_N-1C-inRing",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 R!H u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 R!H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 N   u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 R!H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_4R!H->N",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 N   u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 N   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 N   u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 C   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_Ext-1C-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,S}
2 *3 N   u0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 C   u0 {2,S}
5    R!H u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_Ext-1C-R_2N-inRing",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,S}
2 *3 N   u0 r1 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 C   u0 {2,S}
5    R!H u0 r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_Ext-1C-R_N-2N-inRing",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {5,S}
2 *3 N   u0 r0 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 C   u0 {2,S}
5    R!H u0 r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 N   u0 r1 {1,S} {4,S}
3 *1 R!H u0 {1,D}
4 *4 C   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_3R!H->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 C u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_3R!H->N_Ext-4BrCClF-R_5R!H->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 N u0 r0 {1,D}
4 *4 C u0 r1 {2,S} {5,D}
5    C u0 r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_3R!H->N_Ext-4BrCClF-R_N-5R!H->C",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 N                      u0 r1 {1,S} {4,S}
3 *1 N                      u0 r0 {1,D}
4 *4 C                      u0 r1 {2,S} {5,D}
5    [N,P,F,I,Br,Cl,O,Si,S] u0 r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_N-3R!H->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_N-3R!H->N_Ext-4BrCClF-R_5R!H->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 r1 {1,S} {4,S}
3 *1 O u0 r0 {1,D}
4 *4 C u0 r1 {2,S} {5,D}
5    C u0 r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 28,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_N-3R!H->N_Ext-4BrCClF-R_N-5R!H->C",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 N                      u0 r1 {1,S} {4,S}
3 *1 O                      u0 r0 {1,D}
4 *4 C                      u0 r1 {2,S} {5,D}
5    [N,P,F,I,Br,Cl,O,Si,S] u0 r1 {4,D}
""",
    kinetics = None,
)

entry(
    index = 29,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_N-2N-inRing",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 r0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 30,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_N-2N-inRing_Ext-4BrCClF-R_5R!H->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 N u0 r0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 {2,S} {5,[S,D,T,B,Q]}
5    N ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 31,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_N-2N-inRing_Ext-4BrCClF-R_5R!H->N_Ext-4BrCClF-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 N   u0 r0 {1,S} {4,S}
3 *1 O   u0 r0 {1,D}
4 *4 C   u0 r0 {2,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
5    N   ux {4,[S,D,T,B,Q]}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 32,
    label = "Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_N-2N-inRing_Ext-4BrCClF-R_N-5R!H->N",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 N                      u0 r0 {1,S} {4,S}
3 *1 O                      u0 {1,D}
4 *4 C                      u0 {2,S} {5,D}
5    [P,F,I,Br,Cl,O,C,Si,S] u0 r0 {4,D}
""",
    kinetics = None,
)

entry(
    index = 33,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N",
    group = 
"""
1 *2 C     u0 r0 {2,S} {3,D}
2 *3 [C,O] u0 {1,S} {4,S}
3 *1 R!H   u0 {1,D}
4 *4 R!H   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 34,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_3R!H->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 C u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 35,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_3R!H->N_Ext-4R!H-R_5R!H->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 C u0 {2,S} {5,[S,D,T,B,Q]}
5    N ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 36,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_3R!H->N_Ext-4R!H-R_5R!H->N_Ext-4R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 O   u0 {1,S} {4,S}
3 *1 N   u0 r0 {1,D}
4 *4 C   u0 {2,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
5    N   ux {4,[S,D,T,B,Q]}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 37,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_3R!H->N_Ext-4R!H-R_N-5R!H->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 N u0 {1,D}
4 *4 C u0 {2,S} {5,D}
5    O ux {4,D}
""",
    kinetics = None,
)

entry(
    index = 38,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_3R!H->N_Ext-4R!H-R_N-5R!H->N_Ext-1C-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {6,[S,D,T,B,Q]}
2 *3 O   u0 {1,S} {4,S}
3 *1 N   u0 r0 {1,D}
4 *4 C   u0 {2,S} {5,D}
5    O   ux {4,D}
6    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 39,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N",
    group = 
"""
1 *2 C     u0 r0 {2,S} {3,D}
2 *3 [C,O] u0 {1,S} {4,S}
3 *1 [C,O] u0 {1,D}
4 *4 R!H   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 40,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C",
    group = 
"""
1 *2 C     u0 r0 {2,S} {3,D}
2 *3 [C,O] u0 {1,S} {4,S}
3 *1 [C,O] u0 {1,D}
4 *4 C     u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 41,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_Ext-3CO-R",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 C u0 {1,D} {5,[S,D,T,B,Q]}
4 *4 C u0 {2,S}
5    F ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 42,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_Ext-3CO-R_Ext-4C-R_6R!H->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 r0 {1,S} {4,S}
3 *1 C u0 {1,D} {5,[S,D,T,B,Q]}
4 *4 C u0 r0 {2,S} {6,[S,D,T,B,Q]}
5    F ux {3,[S,D,T,B,Q]}
6    O u0 r0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 43,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_Ext-3CO-R_Ext-4C-R_N-6R!H->O",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 r0 {1,S} {4,S}
3 *1 C u0 {1,D} {5,[S,D,T,B,Q]}
4 *4 C u0 r0 {2,S} {6,S}
5    F ux {3,[S,D,T,B,Q]}
6    F u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 44,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 C u0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 45,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C_Ext-4C-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 C   u0 {2,S} {5,[S,D,T,B,Q]}
5    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 46,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C_Ext-4C-R_Sp-5R!H-4C",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 C   u0 {2,S} {5,S}
5    R!H ux {4,S}
""",
    kinetics = None,
)

entry(
    index = 47,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C_Ext-4C-R_Sp-5R!H-4C_Ext-1C-R",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D} {6,[S,D,T,B,Q]}
2 *3 C u0 {1,S} {4,S}
3 *1 O u0 {1,D}
4 *4 C u0 {2,S} {5,S}
5    F ux {4,S}
6    F ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 48,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C_Ext-4C-R_Sp-5R!H-4C_Ext-1C-R_Ext-4C-R_Ext-4C-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D} {6,[S,D,T,B,Q]}
2 *3 C   u0 r0 {1,S} {4,S}
3 *1 O   u0 r0 {1,D}
4 *4 C   u0 r0 {2,S} {5,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
5    F   ux {4,S}
6    F   ux {1,[S,D,T,B,Q]}
7    R!H ux {4,[S,D,T,B,Q]}
8    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 49,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C_Ext-4C-R_N-Sp-5R!H-4C",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S}
3 *1 O   u0 {1,D}
4 *4 C   u0 {2,S} {5,[B,D,T,Q]}
5    R!H u0 r0 {4,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 50,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_N-2CO->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 C u0 {1,D}
4 *4 C u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 51,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_N-2CO->C_Ext-4C-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 O   u0 {1,S} {4,S}
3 *1 C   u0 {1,D}
4 *4 C   u0 {2,S} {5,[S,D,T,B,Q]}
5    R!H u0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 52,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_N-2CO->C_Ext-4C-R_5R!H->C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 O u0 {1,S} {4,S}
3 *1 C u0 {1,D}
4 *4 C u0 {2,S} {5,[S,D,T,B,Q]}
5    C u0 r0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 53,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_N-2CO->C_Ext-4C-R_N-5R!H->C",
    group = 
"""
1 *2 C                      u0 r0 {2,S} {3,D}
2 *3 O                      u0 {1,S} {4,S}
3 *1 C                      u0 {1,D}
4 *4 C                      u0 {2,S} {5,[S,D,T,B,Q]}
5    [N,P,F,I,Br,Cl,O,Si,S] u0 r0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 54,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C",
    group = 
"""
1 *2 C         u0 r0 {2,S} {3,D}
2 *3 C         u0 {1,S} {4,S}
3 *1 C         u0 {1,D}
4 *4 [Br,F,Cl] u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 55,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_4BrClF->F",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,D}
2 *3 C u0 {1,S} {4,S}
3 *1 C u0 {1,D}
4 *4 F u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 56,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_4BrClF->F_Ext-2CO-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 C   u0 r0 {1,D}
4 *4 F   u0 {2,S}
5    R!H ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 57,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 C       u0 {1,S} {4,S}
3 *1 C       u0 {1,D}
4 *4 [Br,Cl] u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 58,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F_Ext-2CO-R",
    group = 
"""
1 *2 C       u0 r0 {2,S} {3,D}
2 *3 C       u0 {1,S} {4,S} {5,S}
3 *1 C       u0 {1,D}
4 *4 [Br,Cl] u0 {2,S}
5    F       u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 59,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F_Ext-2CO-R_4BrCl->Br",
    group = 
"""
1 *2 C  u0 r0 {2,S} {3,D}
2 *3 C  u0 r0 {1,S} {4,S} {5,S}
3 *1 C  u0 {1,D}
4 *4 Br u0 r0 {2,S}
5    F  u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 60,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F_Ext-2CO-R_N-4BrCl->Br",
    group = 
"""
1 *2 C  u0 r0 {2,S} {3,D}
2 *3 C  u0 r0 {1,S} {4,S} {5,S}
3 *1 C  u0 {1,D}
4 *4 Cl u0 r0 {2,S}
5    F  u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 61,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F_4BrCl->Br",
    group = 
"""
1 *2 C  u0 r0 {2,S} {3,D}
2 *3 C  u0 {1,S} {4,S}
3 *1 C  u0 {1,D}
4 *4 Br u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 62,
    label = "Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F_N-4BrCl->Br",
    group = 
"""
1 *2 C  u0 r0 {2,S} {3,D}
2 *3 C  u0 {1,S} {4,S}
3 *1 C  u0 {1,D}
4 *4 Cl u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 63,
    label = "Root_N-1R!H->C",
    group = 
"""
1 *2 O u0 {2,S} {3,D}
2 *3 C u0 {1,S} {4,S}
3 *1 C u0 {1,D}
4 *4 C u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 64,
    label = "Root_N-1R!H->C_Ext-2R!H-R",
    group = 
"""
1 *2 O   u0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 C   u0 {1,D}
4 *4 C   u0 {2,S}
5    R!H ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 65,
    label = "Root_N-1R!H->C_Ext-2R!H-R_Ext-2R!H-R",
    group = 
"""
1 *2 O   u0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
3 *1 C   u0 {1,D}
4 *4 C   u0 {2,S}
5    R!H ux {2,[S,D,T,B,Q]}
6    R!H ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 66,
    label = "Root_N-1R!H->C_Ext-2R!H-R_Ext-2R!H-R_Ext-4R!H-R_7R!H->C",
    group = 
"""
1 *2 O   u0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
3 *1 C   u0 {1,D}
4 *4 C   u0 {2,S} {7,S}
5    R!H ux {2,[S,D,T,B,Q]}
6    R!H ux {2,[S,D,T,B,Q]}
7    C   u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 67,
    label = "Root_N-1R!H->C_Ext-2R!H-R_Ext-2R!H-R_Ext-4R!H-R_N-7R!H->C",
    group = 
"""
1 *2 O   u0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
3 *1 C   u0 {1,D}
4 *4 C   u0 {2,S} {7,S}
5    R!H ux {2,[S,D,T,B,Q]}
6    R!H ux {2,[S,D,T,B,Q]}
7    F   u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 68,
    label = "Root_N-1R!H->C_Ext-2R!H-R_Ext-4R!H-R",
    group = 
"""
1 *2 O   u0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 C   u0 {1,D}
4 *4 C   u0 {2,S} {6,[S,D,T,B,Q]}
5    C   ux {2,[S,D,T,B,Q]}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 69,
    label = "Root_N-1R!H->C_Ext-2R!H-R_Ext-4R!H-R_Ext-3R!H-R",
    group = 
"""
1 *2 O   u0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 C   u0 {1,D} {7,S}
4 *4 C   u0 {2,S} {6,[S,D,T,B,Q]}
5    C   ux {2,[S,D,T,B,Q]}
6    R!H ux {4,[S,D,T,B,Q]}
7    F   u0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 70,
    label = "Root_N-1R!H->C_Ext-2R!H-R_Ext-4R!H-R_Ext-3R!H-R_6R!H->C",
    group = 
"""
1 *2 O u0 {2,S} {3,D}
2 *3 C u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 C u0 {1,D} {7,S}
4 *4 C u0 {2,S} {6,[S,D,T,B,Q]}
5    C ux {2,[S,D,T,B,Q]}
6    C ux {4,[S,D,T,B,Q]}
7    F u0 r0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 71,
    label = "Root_N-1R!H->C_Ext-2R!H-R_Ext-4R!H-R_Ext-3R!H-R_N-6R!H->C",
    group = 
"""
1 *2 O u0 {2,S} {3,D}
2 *3 C u0 {1,S} {4,S} {5,[S,D,T,B,Q]}
3 *1 C u0 {1,D} {7,S}
4 *4 C u0 {2,S} {6,[S,D,T,B,Q]}
5    C ux {2,[S,D,T,B,Q]}
6    F ux {4,[S,D,T,B,Q]}
7    F u0 r0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 72,
    label = "Root_N-1R!H->C_Ext-4R!H-R",
    group = 
"""
1 *2 O   u0 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S}
3 *1 C   u0 {1,D}
4 *4 C   u0 {2,S} {5,[S,D,T,B,Q]}
5    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_1R!H->C
        L3: Root_1R!H->C_1C-inRing
            L4: Root_1R!H->C_1C-inRing_2R!H->N
                L5: Root_1R!H->C_1C-inRing_2R!H->N_Ext-4R!H-R_5R!H->C
                    L6: Root_1R!H->C_1C-inRing_2R!H->N_Ext-4R!H-R_5R!H->C_Ext-1C-R
                        L7: Root_1R!H->C_1C-inRing_2R!H->N_Ext-4R!H-R_5R!H->C_Ext-1C-R_3R!H->N
                        L7: Root_1R!H->C_1C-inRing_2R!H->N_Ext-4R!H-R_5R!H->C_Ext-1C-R_N-3R!H->N
                L5: Root_1R!H->C_1C-inRing_2R!H->N_Ext-4R!H-R_N-5R!H->C
            L4: Root_1R!H->C_1C-inRing_N-2R!H->N
                L5: Root_1R!H->C_1C-inRing_N-2R!H->N_4R!H->N
                L5: Root_1R!H->C_1C-inRing_N-2R!H->N_N-4R!H->N
                    L6: Root_1R!H->C_1C-inRing_N-2R!H->N_N-4R!H->N_Ext-1C-R
                    L6: Root_1R!H->C_1C-inRing_N-2R!H->N_N-4R!H->N_Ext-4C-R_5R!H->C
                    L6: Root_1R!H->C_1C-inRing_N-2R!H->N_N-4R!H->N_Ext-4C-R_N-5R!H->C
        L3: Root_1R!H->C_N-1C-inRing
            L4: Root_1R!H->C_N-1C-inRing_2R!H->N
                L5: Root_1R!H->C_N-1C-inRing_2R!H->N_4R!H->N
                L5: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N
                    L6: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_Ext-1C-R
                        L7: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_Ext-1C-R_2N-inRing
                        L7: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_Ext-1C-R_N-2N-inRing
                    L6: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing
                        L7: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_3R!H->N
                            L8: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_3R!H->N_Ext-4BrCClF-R_5R!H->C
                            L8: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_3R!H->N_Ext-4BrCClF-R_N-5R!H->C
                        L7: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_N-3R!H->N
                            L8: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_N-3R!H->N_Ext-4BrCClF-R_5R!H->C
                            L8: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_2N-inRing_N-3R!H->N_Ext-4BrCClF-R_N-5R!H->C
                    L6: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_N-2N-inRing
                        L7: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_N-2N-inRing_Ext-4BrCClF-R_5R!H->N
                            L8: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_N-2N-inRing_Ext-4BrCClF-R_5R!H->N_Ext-4BrCClF-R
                        L7: Root_1R!H->C_N-1C-inRing_2R!H->N_N-4R!H->N_N-2N-inRing_Ext-4BrCClF-R_N-5R!H->N
            L4: Root_1R!H->C_N-1C-inRing_N-2R!H->N
                L5: Root_1R!H->C_N-1C-inRing_N-2R!H->N_3R!H->N
                    L6: Root_1R!H->C_N-1C-inRing_N-2R!H->N_3R!H->N_Ext-4R!H-R_5R!H->N
                        L7: Root_1R!H->C_N-1C-inRing_N-2R!H->N_3R!H->N_Ext-4R!H-R_5R!H->N_Ext-4R!H-R
                    L6: Root_1R!H->C_N-1C-inRing_N-2R!H->N_3R!H->N_Ext-4R!H-R_N-5R!H->N
                        L7: Root_1R!H->C_N-1C-inRing_N-2R!H->N_3R!H->N_Ext-4R!H-R_N-5R!H->N_Ext-1C-R
                L5: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N
                    L6: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C
                        L7: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_Ext-3CO-R
                            L8: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_Ext-3CO-R_Ext-4C-R_6R!H->O
                            L8: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_Ext-3CO-R_Ext-4C-R_N-6R!H->O
                        L7: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C
                            L8: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C_Ext-4C-R
                                L9: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C_Ext-4C-R_Sp-5R!H-4C
                                    L10: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C_Ext-4C-R_Sp-5R!H-4C_Ext-1C-R
                                        L11: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C_Ext-4C-R_Sp-5R!H-4C_Ext-1C-R_Ext-4C-R_Ext-4C-R
                                L9: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_2CO->C_Ext-4C-R_N-Sp-5R!H-4C
                        L7: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_N-2CO->C
                            L8: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_N-2CO->C_Ext-4C-R
                                L9: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_N-2CO->C_Ext-4C-R_5R!H->C
                                L9: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_4R!H->C_N-2CO->C_Ext-4C-R_N-5R!H->C
                    L6: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C
                        L7: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_4BrClF->F
                            L8: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_4BrClF->F_Ext-2CO-R
                        L7: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F
                            L8: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F_Ext-2CO-R
                                L9: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F_Ext-2CO-R_4BrCl->Br
                                L9: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F_Ext-2CO-R_N-4BrCl->Br
                            L8: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F_4BrCl->Br
                            L8: Root_1R!H->C_N-1C-inRing_N-2R!H->N_N-3R!H->N_N-4R!H->C_N-4BrClF->F_N-4BrCl->Br
    L2: Root_N-1R!H->C
        L3: Root_N-1R!H->C_Ext-2R!H-R
            L4: Root_N-1R!H->C_Ext-2R!H-R_Ext-2R!H-R
                L5: Root_N-1R!H->C_Ext-2R!H-R_Ext-2R!H-R_Ext-4R!H-R_7R!H->C
                L5: Root_N-1R!H->C_Ext-2R!H-R_Ext-2R!H-R_Ext-4R!H-R_N-7R!H->C
            L4: Root_N-1R!H->C_Ext-2R!H-R_Ext-4R!H-R
                L5: Root_N-1R!H->C_Ext-2R!H-R_Ext-4R!H-R_Ext-3R!H-R
                    L6: Root_N-1R!H->C_Ext-2R!H-R_Ext-4R!H-R_Ext-3R!H-R_6R!H->C
                    L6: Root_N-1R!H->C_Ext-2R!H-R_Ext-4R!H-R_Ext-3R!H-R_N-6R!H->C
        L3: Root_N-1R!H->C_Ext-4R!H-R
"""
)

