#!/usr/bin/env python
# encoding: utf-8

name = "CO2_Elimination_From_Lactone_Ether/groups"
shortDesc = ""
longDesc = """

                        F                                               F
                        |                                               |
*1O = *2C - *3C - *4O - C   <=>  *1O = *2C = *5O    +     *3C- = *4O+ - C  
          \ / 
          *5O

"""

template(reactants=["Root"], products=["CFO_", "R_F"], ownReverse=False)

reversible = True
reverse = "association_via_CO_CF_bond_formation"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*3', 1, '*5'],
    ['BREAK_BOND', '*2', 1, '*3'],
    ['CHANGE_BOND', '*2', 1, '*5'],
    ['CHANGE_BOND', '*4', 1, '*3'],
    ['LOSE_PAIR', '*4', 1],
    ['GAIN_PAIR', '*3', 1],    
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 O u0 {2,D}
2 *2 C u0 {1,D} {3,S} {5,S}
3 *3 C u0 {2,S} {4,S} {5,S}
4 *4 O u0 {3,S} {6,S}
5 *5 O u0 {2,S} {3,S}
6 C u0 {4,S} {7,S}
7 F1s u0 {6,S}
""",
    kinetics = None,
)


         