#!/usr/bin/env python
# encoding: utf-8

name = "Brown pdep reaction library"
shortDesc = "pressure dependent reactions for CH2F2 decomposition (from Brown)"
longDesc = """
Sources:
Quantifying the effect of difluoromethane on
ignition delay times of propane
Eduardo H. Guzman, Nora Khalil, Rachel A. Schwind,
Richard H. West, C. Franklin Goldsmith,
2023

"""
autoGenerated=False


entry(
    index = 0,
    label = "CH4 + F <=> CH3F + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.570000e+04,'cm^3/mol/s'), n=2.58, Ea=(84.9,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 1,
    label = "CH3F + F <=> CH2F2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.470000e+04,'cm^3/mol/s'), n=2.61, Ea=(87.4,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 2,
    label = "CH2F2 + F <=> CHF3 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.620000e+03,'cm^3/mol/s'), n=2.73, Ea=(116.8,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 3,
    label = "CHF3 + F <=> CF4 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.250000e-70,'cm^3/mol/s'), n=22.86, Ea=(70.0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 4,
    label = "CH2 + F <=> CHF + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.020000e+13,'cm^3/mol/s'), n=0.01, Ea=(0.08,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 5,
    label = "CH2 + F <=> CH + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.340000e+13,'cm^3/mol/s'), n=0.07, Ea=(-0.34,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 6,
    label = "CHF + F <=> CF2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.570000e+14,'cm^3/mol/s'), n=-0.14, Ea=(0.58,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 7,
    label = "CHF + F <=> CF + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.290000e+11,'cm^3/mol/s'), n=0.53, Ea=(-1.89,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 8,
    label = "CHF + O <=> CF + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.260000e+07,'cm^3/mol/s'), n=1.35, Ea=(-4.69,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 9,
    label = "CHF + O <=> FCO + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.450000e+12,'cm^3/mol/s'), n=0.27, Ea=(-1.03,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 10,
    label = "CF + OH <=> FCO + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.640000e+12,'cm^3/mol/s'), n=0.24, Ea=(-1.26,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 11,
    label = "FCO + H <=> CO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.130000e+13,'cm^3/mol/s'), n=0.04, Ea=(0.65,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 12,
    label = "CHF2 + O <=> CF2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.290000e+11,'cm^3/mol/s'), n=0.54, Ea=(-1.53,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 13,
    label = "CHF2 + O <=> CF2O + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.170000e+13,'cm^3/mol/s'), n=-0.09, Ea=(0.23,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 14,
    label = "CHF2 + O <=> FCO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.860000e+12,'cm^3/mol/s'), n=0.25, Ea=(-0.99,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 15,
    label = "CF2 + OH <=> CF2O + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.620000e+13,'cm^3/mol/s'), n=-0.16, Ea=(0.71,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 16,
    label = "CF2 + OH <=> FCO + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.360000e+10,'cm^3/mol/s'), n=0.6, Ea=(-1.46,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 17,
    label = "FCO + OH <=> CO2 + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.320000e+13,'cm^3/mol/s'), n=0.04, Ea=(-0.03,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)
    

entry(
    index = 18,
    label = "CF2O + H2O <=> CFOOH + HF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.560000e-01,'cm^3/mol/s'), n=3.39, Ea=(152.5,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K')),
    shortDesc = """From Brown difluoromethane mech""",
    longDesc = 
"""
Electronic structures done using ANL0 compound method. 
Torsional scans with  M06-2X/cc-pVTZ. 
""",
)

#"Franklin's edits" Nora K. built an RMG model of C3H8 and CH2F2. Original RMG model contained two pdep reactions: 1) CHF2 + O2 = CHF2OO and 2) CHF2 + O2 = OH + CF2O. These rates were recalculated by Franklin Goldsmith at Brown University. 

entry(
    index = 19,
    label = "O2 + CHF2 <=> CHF2OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.19e+34,'cm^3/(mol*s)'), n=-7.27, Ea=(19.81,'kJ/mol'), T0=(1,'K')),
    shortDesc = """From Franklin Goldsmith: chf2 + o2 --> chf2oo [3.19E+34    -7.27  19.81] (Ea is in kJ/mol)""",
)

entry(
    index = 20,
    label = "O2 + CHF2 <=> OH + CF2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.53e+16,'cm^3/(mol*s)'), n=-2.93, Ea=(152.70,'kJ/mol'), T0=(1,'K')),
    shortDesc = """From Franklin Goldsmith: chf2 + o2 --> oh + cf2o: [1.53E+16    -2.93  152.70] (Ea is in kJ/mol)""",
)