#!/usr/bin/env python
# encoding: utf-8

name = "PFAS_HPL_multiple_matches"

autoGenerated=False

entry(
    index = 60,
    label = "C3F8 <=> C2F6+CF2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.18E+10,'1/s'), n=1.21, Ea=(115318.91,'cal/mol'), T0=(1,'K')),
    shortDesc = u"""The chemkin file reaction is C3F8 <=> C2F6+CF2""",
)

#matched twice to 1,2_Insertion_Carbene, not sure why it never added it in...