#!/usr/bin/env python
# encoding: utf-8

name = "Enol_Ether_Formation/groups"
shortDesc = ""
longDesc = """
                                     *4F
                                      |
C - *1O - *2C - *3C - *4F <=>  *1O - *2C = *3C

or with resonance

                                    *4F
                                    |
*1O+ = *2C- - *3C - *4F <=>  *1O - *2C = *3C
"""

template(reactants=["Root"], products=['perfluorinated_alkene'], ownReverse=False)

reversible = True
reverse = "Enol_Ether_Transformation"
         
reactantNum = 1

productNum = 1
         
autoGenerated = True

# recipe(actions=[
#     ['BREAK_BOND', '*3', 1, '*4'],
#     ['FORM_BOND', '*2', 1, '*4'],
#     ['CHANGE_BOND', '*3', 1, '*2'],
#     ['CHANGE_BOND', '*1', -1, '*2'],
# ])

recipe(actions=[
    ['BREAK_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*2', 1, '*4'],
    ['CHANGE_BOND', '*3', 1, '*2'],
    ['LOSE_PAIR', '*2', 1],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 O u0 p2 {2,S} {5,S}
2 *2 C u0 p1 {1,S} {3,S}
3 *3 C u0 p0 {2,S} {4,S}
4 *4 F1s u0 {3,S}
5  C  u0 p0 c0 {1,S}
""",
    kinetics = None,
)


# entry(
#     index = 0,
#     label = "Root",
#     group = 
# """
# 1 *1 O u0 c+1 {2,D}
# 2 *2 C u0 c-1 {1,D} {3,S}
# 3 *3 C u0 c0 {2,S} {4,S}
# 4 *4 F1s u0 {3,S}
# """,
#     kinetics = None,
# )