#!/usr/bin/env python
# encoding: utf-8

name = "Enol_Ether_Formation/groups"
shortDesc = ""
longDesc = """
                                    *4F
                                    |
*1O+ = *2C- - *3C - *4F <=>  *1O - *2C = *3C

"""

template(reactants=["Root"], products=['perfluorinated_alkene'], ownReverse=False)

reversible = True
reverse = "Enol_Ether_Transformation"
         
reactantNum = 1

productNum = 1
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*2', 1, '*4'],
    ['CHANGE_BOND', '*3', 1, '*2'],
    ['CHANGE_BOND', '*1', -1, '*2'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 O u0 c+1 {2,D}
2 *2 C u0 c-1 {1,D} {3,S}
3 *3 C u0 {2,S} {4,S}
4 *4 F1s u0 {3,S}
""",
    kinetics = None,
)
