#!/usr/bin/env python
# encoding: utf-8

name = "CO2_Elimination_From_Carboxylic_Acid/groups"
shortDesc = ""
longDesc = """

*1R - F
  \            
   *2C = *3O   <=>  *4O = *2C = *3O     +    F - *1R - *5H
  /
 *4O - *5H

"""

template(reactants=["Root"], products=["CO2", "R_H"], ownReverse=False)

reversible = True
reverse = "CO2_addition"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*4', 1, '*5'],
    ['BREAK_BOND', '*2', 1, '*1'],
    ['CHANGE_BOND', '*4', 1, '*2'],
    ['FORM_BOND', '*5', 1, '*1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 R u[0,1,2] {2,S} {6,S}
2 *2 C u0 {1,S} {3,D} {4,S}
3 *3 O u0 {2,D}
4 *4 O u0 {2,S} {5,S}
5 *5 H u0 {4,S}
6 F1s u0 {1,S}
""",
    kinetics = None,
)


         