#!/usr/bin/env python
# encoding: utf-8

name = "CO_CF_bond_dissociation/groups"
shortDesc = ""
longDesc = """
one carbon-oxygen and one carbon-fluorine bond is broken (although not on the same carbon). Oxygen and fluorine then bond to the "opposite" carbon. 


    *4F
    |
R - *1C - *2O - *3C - R      <-->   R - *1C = *2O    +   *4F - *3C - R
    |                                    |
    F                                    F
"""

template(reactants=["Root"], products=["CFO_", "R_F"], ownReverse=False)

reverse = "association_via_CO_CF_bond_formation"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*4', 1, '*1'],
    ['BREAK_BOND', '*2', 1, '*3'],
    ['CHANGE_BOND', '*1', 1, '*2'],
    ['FORM_BOND', '*4', 1, '*3'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 O       u0         {2,S} {3,S}
2 *1 C       u0         p0 {1,S} {4,S}
3 *3 C       u[0,1,2,3] {1,S} {5,S}
4 *4 [F1s,H] u0         {2,S}
5    R       u[0,1,2,3] {3,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-3C-R",
    group = 
"""
1 *2 O       u0         {2,S} {3,S}
2 *1 C       u0         p0 {1,S} {4,S}
3 *3 C       u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 [F1s,H] u0         {2,S}
5    R       u[0,1,2,3] {3,S}
6    R!H     ux         {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-3C-R_6R!H->C",
    group = 
"""
1 *2 O       u0         {2,S} {3,S}
2 *1 C       u0         p0 {1,S} {4,S}
3 *3 C       u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 [F1s,H] u0         {2,S}
5    R       u[0,1,2,3] {3,S}
6    C       ux         {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_Ext-3C-R_6R!H->C_4F1sH->H",
    group = 
"""
1 *2 O u0 {2,S} {3,S}
2 *1 C u0 p0 {1,S} {4,S}
3 *3 C u0 {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 H u0 {2,S}
5    H u0 {3,S}
6    C ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_Ext-3C-R_6R!H->C_4F1sH->H_Sp-6C-3C",
    group = 
"""
1 *2 O u0 {2,S} {3,S}
2 *1 C u0 p0 {1,S} {4,S}
3 *3 C u0 {1,S} {5,S} {6,S}
4 *4 H u0 {2,S}
5    H u0 {3,S}
6    C ux {3,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_Ext-3C-R_6R!H->C_4F1sH->H_Sp-6C-3C_Ext-2C-R",
    group = 
"""
1 *2 O   u0 r0 {2,S} {3,S}
2 *1 C   u0 p0 r0 {1,S} {4,S} {7,[S,D,T,B,Q]}
3 *3 C   u0 r0 {1,S} {5,S} {6,S}
4 *4 H   u0 r0 {2,S}
5    H   u0 r0 {3,S}
6    C   ux {3,S}
7    R!H ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_Ext-3C-R_6R!H->C_4F1sH->H_N-Sp-6C-3C",
    group = 
"""
1 *2 O u0 {2,S} {3,S}
2 *1 C u0 p0 {1,S} {4,S}
3 *3 C u0 {1,S} {5,S} {6,D}
4 *4 H u0 {2,S}
5    H u0 {3,S}
6    C ux {3,D}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_Ext-3C-R_6R!H->C_4F1sH->H_N-Sp-6C-3C_Ext-2C-R",
    group = 
"""
1 *2 O   u0 r0 {2,S} {3,S}
2 *1 C   u0 p0 r0 {1,S} {4,S} {7,[S,D,T,B,Q]}
3 *3 C   u0 r0 {1,S} {5,S} {6,D}
4 *4 H   u0 r0 {2,S}
5    H   u0 r0 {3,S}
6    C   ux {3,D}
7    R!H ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_Ext-3C-R_6R!H->C_N-4F1sH->H",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 F1s u0         {2,S}
5    R   u[0,1,2,3] {3,S}
6    C   u0         {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-3C-R",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
4 *4 F1s u0         {2,S}
5    H   u[0,1,2,3] {3,S}
6    C   u0         {3,[S,D,T,B,Q]}
7    F   ux         {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-3C-R_Ext-6C-R_Ext-6C-R_8R!H->C",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S} {8,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
4 *4 F1s u0         {2,S}
5    H   u[0,1,2,3] {3,S}
6    C   u0         {3,[S,D,T,B,Q]}
7    F   ux         {3,[S,D,T,B,Q]}
8    C   u0         {2,S}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-3C-R_Ext-6C-R_Ext-6C-R_8R!H->C_Ext-8C-R_9R!H->C",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S} {8,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
4 *4 F1s u0         {2,S}
5    H   u[0,1,2,3] {3,S}
6    C   u0         r0 {3,[S,D,T,B,Q]}
7    F   ux         {3,[S,D,T,B,Q]}
8    C   u0         r0 {2,S} {9,S}
9    C   u0         r0 {8,S}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-3C-R_Ext-6C-R_Ext-6C-R_8R!H->C_Ext-8C-R_N-9R!H->C",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S} {8,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
4 *4 F1s u0         {2,S}
5    H   u[0,1,2,3] {3,S}
6    C   u0         r0 {3,[S,D,T,B,Q]}
7    F   ux         {3,[S,D,T,B,Q]}
8    C   u0         r0 {2,S} {9,S}
9    F   u0         r0 {8,S}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-3C-R_Ext-6C-R_Ext-6C-R_N-8R!H->C",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S} {8,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
4 *4 F1s u0         {2,S}
5    H   u[0,1,2,3] {3,S}
6    C   u0         r0 {3,[S,D,T,B,Q]}
7    F   ux         {3,[S,D,T,B,Q]}
8    F   u0         r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-6C-R_Ext-6C-R_7R!H->C",
    group = 
"""
1 *2 O   u0 {2,S} {3,S}
2 *1 C   u0 p0 {1,S} {4,S} {7,S}
3 *3 C   u0 {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 F1s u0 {2,S}
5    F   u0 {3,S}
6    C   u0 {3,[S,D,T,B,Q]}
7    C   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-6C-R_Ext-6C-R_7R!H->C_Ext-7C-R_8R!H->C",
    group = 
"""
1 *2 O   u0 r0 {2,S} {3,S}
2 *1 C   u0 p0 r0 {1,S} {4,S} {7,S}
3 *3 C   u0 r0 {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 F1s u0 r0 {2,S}
5    F   u0 r0 {3,S}
6    C   u0 r0 {3,[S,D,T,B,Q]}
7    C   u0 r0 {2,S} {8,S}
8    C   u0 r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-6C-R_Ext-6C-R_7R!H->C_Ext-7C-R_N-8R!H->C",
    group = 
"""
1 *2 O   u0 r0 {2,S} {3,S}
2 *1 C   u0 p0 r0 {1,S} {4,S} {7,S}
3 *3 C   u0 r0 {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 F1s u0 r0 {2,S}
5    F   u0 r0 {3,S}
6    C   u0 r0 {3,[S,D,T,B,Q]}
7    C   u0 r0 {2,S} {8,S}
8    F   u0 r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-6C-R_Ext-6C-R_N-7R!H->C",
    group = 
"""
1 *2 O   u0 r0 {2,S} {3,S}
2 *1 C   u0 p0 r0 {1,S} {4,S} {7,S}
3 *3 C   u0 r0 {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 F1s u0 r0 {2,S}
5    F   u0 r0 {3,S}
6    C   u0 r0 {3,[S,D,T,B,Q]}
7    F   u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_Ext-3C-R_N-6R!H->C",
    group = 
"""
1 *2 O       u0         {2,S} {3,S}
2 *1 C       u0         p0 {1,S} {4,S}
3 *3 C       u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 [F1s,H] u0         {2,S}
5    C       u[0,1,2,3] {3,S}
6    O       ux         {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_Ext-3C-R_N-6R!H->C_4F1sH->H",
    group = 
"""
1 *2 O u0         {2,S} {3,S}
2 *1 C u0         p0 {1,S} {4,S}
3 *3 C u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 H u0         {2,S}
5    C u[0,1,2,3] {3,S}
6    O u0         {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_Ext-3C-R_N-6R!H->C_4F1sH->H_Ext-2C-R",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S} {7,[S,D,T,B,Q]}
3 *3 C   u[0,1,2,3] {1,S} {5,S} {6,[S,D,T,B,Q]}
4 *4 H   u0         {2,S}
5    C   u[0,1,2,3] {3,S}
6    O   u0         r0 {3,[S,D,T,B,Q]}
7    R!H ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_Ext-3C-R_N-6R!H->C_N-4F1sH->H",
    group = 
"""
1 *2 O   u0 {2,S} {3,S}
2 *1 C   u0 p0 {1,S} {4,S}
3 *3 C   u0 {1,S} {5,S} {6,D}
4 *4 F1s u0 {2,S}
5    C   u0 {3,S}
6    O   ux {3,D}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_Ext-3C-R_N-6R!H->C_N-4F1sH->H_Ext-5R-R_Ext-5R-R_7R!H->C",
    group = 
"""
1 *2 O   u0 {2,S} {3,S}
2 *1 C   u0 p0 {1,S} {4,S} {7,S}
3 *3 C   u0 {1,S} {5,S} {6,D}
4 *4 F1s u0 {2,S}
5    C   u0 {3,S}
6    O   ux {3,D}
7    C   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_Ext-3C-R_N-6R!H->C_N-4F1sH->H_Ext-5R-R_Ext-5R-R_7R!H->C_Ext-7C-R_8R!H->C",
    group = 
"""
1 *2 O   u0 r0 {2,S} {3,S}
2 *1 C   u0 p0 r0 {1,S} {4,S} {7,S}
3 *3 C   u0 r0 {1,S} {5,S} {6,D}
4 *4 F1s u0 r0 {2,S}
5    C   u0 r0 {3,S}
6    O   ux {3,D}
7    C   u0 r0 {2,S} {8,S}
8    C   u0 r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_Ext-3C-R_N-6R!H->C_N-4F1sH->H_Ext-5R-R_Ext-5R-R_7R!H->C_Ext-7C-R_N-8R!H->C",
    group = 
"""
1 *2 O   u0 r0 {2,S} {3,S}
2 *1 C   u0 p0 r0 {1,S} {4,S} {7,S}
3 *3 C   u0 r0 {1,S} {5,S} {6,D}
4 *4 F1s u0 r0 {2,S}
5    C   u0 r0 {3,S}
6    O   ux {3,D}
7    C   u0 r0 {2,S} {8,S}
8    F   u0 r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_Ext-3C-R_N-6R!H->C_N-4F1sH->H_Ext-5R-R_Ext-5R-R_N-7R!H->C",
    group = 
"""
1 *2 O   u0 r0 {2,S} {3,S}
2 *1 C   u0 p0 r0 {1,S} {4,S} {7,S}
3 *3 C   u0 r0 {1,S} {5,S} {6,D}
4 *4 F1s u0 r0 {2,S}
5    C   u0 r0 {3,S}
6    O   ux {3,D}
7    F   u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_4F1sH->H",
    group = 
"""
1 *2 O u0         {2,S} {3,S}
2 *1 C u0         p0 {1,S} {4,S}
3 *3 C u[0,1,2,3] {1,S} {5,S}
4 *4 H u0         {2,S}
5    C u[0,1,2,3] {3,S}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_4F1sH->H_Ext-2C-R_Ext-6R!H-R",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S} {6,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S}
4 *4 H   u0         {2,S}
5    C   u[0,1,2,3] {3,S}
6    C   u0         r0 {2,S} {7,[S,D,T,B,Q]}
7    R!H ux         {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 28,
    label = "Root_N-4F1sH->H",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S}
4 *4 F1s u0         {2,S}
5    C   u[0,1,2,3] {3,S}
""",
    kinetics = None,
)

entry(
    index = 29,
    label = "Root_N-4F1sH->H_Ext-5R-R_Ext-5R-R_6R!H->C",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S} {6,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S}
4 *4 F1s u0         {2,S}
5    C   u[0,1,2,3] {3,S}
6    C   u0         {2,S}
""",
    kinetics = None,
)

entry(
    index = 30,
    label = "Root_N-4F1sH->H_Ext-5R-R_Ext-5R-R_6R!H->C_Ext-6C-R_7R!H->C",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S} {6,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S}
4 *4 F1s u0         {2,S}
5    C   u[0,1,2,3] {3,S}
6    C   u0         r0 {2,S} {7,S}
7    C   u0         r0 {6,S}
""",
    kinetics = None,
)

entry(
    index = 31,
    label = "Root_N-4F1sH->H_Ext-5R-R_Ext-5R-R_6R!H->C_Ext-6C-R_N-7R!H->C",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S} {6,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S}
4 *4 F1s u0         {2,S}
5    C   u[0,1,2,3] {3,S}
6    C   u0         r0 {2,S} {7,S}
7    F   u0         r0 {6,S}
""",
    kinetics = None,
)

entry(
    index = 32,
    label = "Root_N-4F1sH->H_Ext-5R-R_Ext-5R-R_N-6R!H->C",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *1 C   u0         p0 {1,S} {4,S} {6,S}
3 *3 C   u[0,1,2,3] {1,S} {5,S}
4 *4 F1s u0         {2,S}
5    C   u[0,1,2,3] {3,S}
6    F   u0         r0 {2,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-3C-R
        L3: Root_Ext-3C-R_6R!H->C
            L4: Root_Ext-3C-R_6R!H->C_4F1sH->H
                L5: Root_Ext-3C-R_6R!H->C_4F1sH->H_Sp-6C-3C
                    L6: Root_Ext-3C-R_6R!H->C_4F1sH->H_Sp-6C-3C_Ext-2C-R
                L5: Root_Ext-3C-R_6R!H->C_4F1sH->H_N-Sp-6C-3C
                    L6: Root_Ext-3C-R_6R!H->C_4F1sH->H_N-Sp-6C-3C_Ext-2C-R
            L4: Root_Ext-3C-R_6R!H->C_N-4F1sH->H
                L5: Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-3C-R
                    L6: Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-3C-R_Ext-6C-R_Ext-6C-R_8R!H->C
                        L7: Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-3C-R_Ext-6C-R_Ext-6C-R_8R!H->C_Ext-8C-R_9R!H->C
                        L7: Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-3C-R_Ext-6C-R_Ext-6C-R_8R!H->C_Ext-8C-R_N-9R!H->C
                    L6: Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-3C-R_Ext-6C-R_Ext-6C-R_N-8R!H->C
                L5: Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-6C-R_Ext-6C-R_7R!H->C
                    L6: Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-6C-R_Ext-6C-R_7R!H->C_Ext-7C-R_8R!H->C
                    L6: Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-6C-R_Ext-6C-R_7R!H->C_Ext-7C-R_N-8R!H->C
                L5: Root_Ext-3C-R_6R!H->C_N-4F1sH->H_Ext-6C-R_Ext-6C-R_N-7R!H->C
        L3: Root_Ext-3C-R_N-6R!H->C
            L4: Root_Ext-3C-R_N-6R!H->C_4F1sH->H
                L5: Root_Ext-3C-R_N-6R!H->C_4F1sH->H_Ext-2C-R
            L4: Root_Ext-3C-R_N-6R!H->C_N-4F1sH->H
                L5: Root_Ext-3C-R_N-6R!H->C_N-4F1sH->H_Ext-5R-R_Ext-5R-R_7R!H->C
                    L6: Root_Ext-3C-R_N-6R!H->C_N-4F1sH->H_Ext-5R-R_Ext-5R-R_7R!H->C_Ext-7C-R_8R!H->C
                    L6: Root_Ext-3C-R_N-6R!H->C_N-4F1sH->H_Ext-5R-R_Ext-5R-R_7R!H->C_Ext-7C-R_N-8R!H->C
                L5: Root_Ext-3C-R_N-6R!H->C_N-4F1sH->H_Ext-5R-R_Ext-5R-R_N-7R!H->C
    L2: Root_4F1sH->H
        L3: Root_4F1sH->H_Ext-2C-R_Ext-6R!H-R
    L2: Root_N-4F1sH->H
        L3: Root_N-4F1sH->H_Ext-5R-R_Ext-5R-R_6R!H->C
            L4: Root_N-4F1sH->H_Ext-5R-R_Ext-5R-R_6R!H->C_Ext-6C-R_7R!H->C
            L4: Root_N-4F1sH->H_Ext-5R-R_Ext-5R-R_6R!H->C_Ext-6C-R_N-7R!H->C
        L3: Root_N-4F1sH->H_Ext-5R-R_Ext-5R-R_N-6R!H->C
"""
)

