#!/usr/bin/env python
# encoding: utf-8

name = "CO_CF_bond_dissociation/groups"
shortDesc = ""
longDesc = """
one carbon-oxygen and one carbon-fluorine bond is broken (although not on the same carbon). Oxygen and fluorine then bond to the "opposite" carbon. 


    *4F
    |
R - *1C - *2O - *3C - R      <-->   R - *1C = *2O    +   *4F - *3C - R
    |                                    |
    F                                    F
"""

template(reactants=["Root"], products=["CFO_", "R_F"], ownReverse=False)

reverse = "association_via_CO_CF_bond_formation"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*4', 1, '*1'],
    ['BREAK_BOND', '*2', 1, '*3'],
    ['CHANGE_BOND', '*1', 1, '*2'],
    ['FORM_BOND', '*4', 1, '*3'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 C         u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0         {1,S} {3,S}
3 *3 C         u[0,1,2,3] {2,S} {7,S}
4    [F1s,C,H] u0         {1,S}
5    [F1s,C,H] u0         {1,S}
6 *4 F1s       u0         {1,S}
7    R         u[0,1,2,3] {3,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_3C-u0",
    group = 
"""
1 *1 C         u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0         {1,S} {3,S}
3 *3 C         u0         {2,S} {7,S}
4    [F1s,C,H] u0         {1,S}
5    [F1s,C,H] u0         {1,S}
6 *4 F1s       u0         {1,S}
7    R         u[0,1,2,3] {3,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_3C-u0_7R->F",
    group = 
"""
1 *1 C         u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0         {1,S} {3,S}
3 *3 C         u0         {2,S} {7,S}
4    [F1s,C,H] u0         {1,S}
5    [F1s,C,H] u0         {1,S}
6 *4 F1s       u0         {1,S}
7    F         u[0,1,2,3] {3,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s",
    group = 
"""
1 *1 C         u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0         {1,S} {3,S}
3 *3 C         u0         {2,S} {7,S}
4    F1s       u0         {1,S}
5    [F1s,C,H] u0         {1,S}
6 *4 F1s       u0         {1,S}
7    F         u[0,1,2,3] {3,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C",
    group = 
"""
1 *1 C         u0 p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0 {1,S} {3,S}
3 *3 C         u0 {2,S} {7,S} {8,S}
4    F1s       u0 {1,S}
5    [F1s,C,H] u0 {1,S}
6 *4 F1s       u0 {1,S}
7    F         u0 {3,S}
8    C         u0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_5CF1sH->F1s",
    group = 
"""
1 *1 C   u0 p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0 {1,S} {3,S}
3 *3 C   u0 {2,S} {7,S} {8,S}
4    F1s u0 {1,S}
5    F1s u0 {1,S}
6 *4 F1s u0 {1,S}
7    F   u0 {3,S}
8    C   u0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_5CF1sH->F1s_Ext-3C-R",
    group = 
"""
1 *1 C   u0 p0 r0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0 r0 {1,S} {3,S}
3 *3 C   u0 r0 {2,S} {7,S} {8,S} {9,[S,D,T,B,Q]}
4    F1s u0 {1,S}
5    F1s u0 {1,S}
6 *4 F1s u0 {1,S}
7    F   u0 r0 {3,S}
8    C   u0 r0 {3,S}
9    R!H ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_N-5CF1sH->F1s",
    group = 
"""
1 *1 C   u0 p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0 {1,S} {3,S}
3 *3 C   u0 {2,S} {7,S} {8,S}
4    F1s u0 {1,S}
5    C   u0 {1,S}
6 *4 F1s u0 {1,S}
7    F   u0 {3,S}
8    C   u0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_9R!H->C",
    group = 
"""
1 *1 C   u0 p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0 {1,S} {3,S}
3 *3 C   u0 {2,S} {7,S} {8,S}
4    F1s u0 {1,S}
5    C   u0 {1,S} {9,[S,D,T,B,Q]}
6 *4 F1s u0 {1,S}
7    F   u0 {3,S}
8    C   u0 {3,S}
9    C   ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_9R!H->C_Ext-3C-R",
    group = 
"""
1  *1 C   u0 p0 r0 {2,S} {4,S} {5,S} {6,S}
2  *2 O   u0 r0 {1,S} {3,S}
3  *3 C   u0 r0 {2,S} {7,S} {8,S} {10,[S,D,T,B,Q]}
4     F1s u0 {1,S}
5     C   u0 r0 {1,S} {9,[S,D,T,B,Q]}
6  *4 F1s u0 {1,S}
7     F   u0 r0 {3,S}
8     C   u0 r0 {3,S}
9     C   ux {5,[S,D,T,B,Q]}
10    R!H ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_N-9R!H->C",
    group = 
"""
1 *1 C   u0 p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0 {1,S} {3,S}
3 *3 C   u0 {2,S} {7,S} {8,S}
4    F1s u0 {1,S}
5    C   u0 {1,S} {9,[S,D,T,B,Q]}
6 *4 F1s u0 {1,S}
7    F   u0 {3,S}
8    C   u0 {3,S}
9    F   ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_N-9R!H->C_Ext-3C-R",
    group = 
"""
1  *1 C   u0 p0 r0 {2,S} {4,S} {5,S} {6,S}
2  *2 O   u0 r0 {1,S} {3,S}
3  *3 C   u0 r0 {2,S} {7,S} {8,S} {10,[S,D,T,B,Q]}
4     F1s u0 {1,S}
5     C   u0 r0 {1,S} {9,[S,D,T,B,Q]}
6  *4 F1s u0 {1,S}
7     F   u0 r0 {3,S}
8     C   u0 r0 {3,S}
9     F   ux {5,[S,D,T,B,Q]}
10    R!H ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_N-Sp-8R!H-3C",
    group = 
"""
1 *1 C         u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0         {1,S} {3,S}
3 *3 C         u0         {2,S} {7,S} {8,[B,D,T,Q]}
4    F1s       u0         {1,S}
5    [F1s,C,H] u0         {1,S}
6 *4 F1s       u0         {1,S}
7    F         u[0,1,2,3] {3,S}
8    C         ux         {3,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_N-Sp-8R!H-3C_5CF1sH->F1s",
    group = 
"""
1 *1 C   u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0         {1,S} {3,S}
3 *3 C   u0         {2,S} {7,S} {8,[B,D,T,Q]}
4    F1s u0         {1,S}
5    F1s u0         {1,S}
6 *4 F1s u0         {1,S}
7    F   u[0,1,2,3] {3,S}
8    C   ux         {3,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_N-Sp-8R!H-3C_N-5CF1sH->F1s",
    group = 
"""
1 *1 C   u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0         {1,S} {3,S}
3 *3 C   u0         {2,S} {7,S} {8,[B,D,T,Q]}
4    F1s u0         {1,S}
5    C   u0         {1,S}
6 *4 F1s u0         {1,S}
7    F   u[0,1,2,3] {3,S}
8    C   ux         {3,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_N-Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_9R!H->C",
    group = 
"""
1 *1 C   u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0         {1,S} {3,S}
3 *3 C   u0         {2,S} {7,S} {8,[B,D,T,Q]}
4    F1s u0         {1,S}
5    C   u0         {1,S} {9,S}
6 *4 F1s u0         {1,S}
7    F   u[0,1,2,3] {3,S}
8    C   ux         {3,[B,D,T,Q]}
9    C   u0         r0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_N-Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_N-9R!H->C",
    group = 
"""
1 *1 C   u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0         {1,S} {3,S}
3 *3 C   u0         {2,S} {7,S} {8,[B,D,T,Q]}
4    F1s u0         {1,S}
5    C   u0         {1,S} {9,S}
6 *4 F1s u0         {1,S}
7    F   u[0,1,2,3] {3,S}
8    C   ux         {3,[B,D,T,Q]}
9    F   u0         r0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_3C-u0_7R->F_N-4CF1sH->F1s",
    group = 
"""
1 *1 C         u0 p0 r0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0 r0 {1,S} {3,S}
3 *3 C         u0 r0 {2,S} {7,S}
4    C         u0 r0 {1,S}
5    [F1s,C,H] u0 r0 {1,S}
6 *4 F1s       u0 r0 {1,S}
7    F         u0 r0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_3C-u0_N-7R->F",
    group = 
"""
1 *1 C         u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0         {1,S} {3,S}
3 *3 C         u0         {2,S} {7,S}
4    [F1s,C,H] u0         {1,S}
5    F1s       u0         {1,S}
6 *4 F1s       u0         {1,S}
7    C         u[0,1,2,3] {3,S}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_3C-u0_N-7R->F_4CF1sH->C",
    group = 
"""
1 *1 C   u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0         {1,S} {3,S}
3 *3 C   u0         {2,S} {7,S}
4    C   u0         {1,S}
5    F1s u0         {1,S}
6 *4 F1s u0         {1,S}
7    C   u[0,1,2,3] {3,S}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_3C-u0_N-7R->F_4CF1sH->C_Ext-3C-R",
    group = 
"""
1 *1 C   u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0         {1,S} {3,S}
3 *3 C   u0         {2,S} {7,S} {8,[S,D,T,B,Q]}
4    C   u0         {1,S}
5    F1s u0         {1,S}
6 *4 F1s u0         {1,S}
7    C   u[0,1,2,3] {3,S}
8    O   ux         {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_3C-u0_N-7R->F_4CF1sH->C_Ext-3C-R_Ext-7CHO-R_Ext-7CHO-R_9R!H->C",
    group = 
"""
1 *1 C   u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0         {1,S} {3,S}
3 *3 C   u0         {2,S} {7,S} {8,[S,D,T,B,Q]}
4    C   u0         {1,S} {9,S}
5    F1s u0         {1,S}
6 *4 F1s u0         {1,S}
7    C   u[0,1,2,3] {3,S}
8    O   ux         {3,[S,D,T,B,Q]}
9    C   u0         r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_3C-u0_N-7R->F_4CF1sH->C_Ext-3C-R_Ext-7CHO-R_Ext-7CHO-R_N-9R!H->C",
    group = 
"""
1 *1 C   u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0         {1,S} {3,S}
3 *3 C   u0         {2,S} {7,S} {8,[S,D,T,B,Q]}
4    C   u0         {1,S} {9,S}
5    F1s u0         {1,S}
6 *4 F1s u0         {1,S}
7    C   u[0,1,2,3] {3,S}
8    O   ux         {3,[S,D,T,B,Q]}
9    F   u0         r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_3C-u0_N-7R->F_4CF1sH->C_Ext-7CHO-R_Ext-7CHO-R_8R!H->C",
    group = 
"""
1 *1 C   u0 p0 r0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0 r0 {1,S} {3,S}
3 *3 C   u0 r0 {2,S} {7,S}
4    C   u0 r0 {1,S} {8,S}
5    F1s u0 r0 {1,S}
6 *4 F1s u0 {1,S}
7    C   u0 r0 {3,S}
8    C   u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_3C-u0_N-7R->F_4CF1sH->C_Ext-7CHO-R_Ext-7CHO-R_N-8R!H->C",
    group = 
"""
1 *1 C   u0 p0 r0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0 r0 {1,S} {3,S}
3 *3 C   u0 r0 {2,S} {7,S}
4    C   u0 r0 {1,S} {8,S}
5    F1s u0 r0 {1,S}
6 *4 F1s u0 {1,S}
7    C   u0 r0 {3,S}
8    F   u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_3C-u0_N-7R->F_N-4CF1sH->C",
    group = 
"""
1 *1 C   u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0         {1,S} {3,S}
3 *3 C   u0         {2,S} {7,S}
4    F1s u0         {1,S}
5    F1s u0         {1,S}
6 *4 F1s u0         {1,S}
7    C   u[0,1,2,3] {3,S}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_3C-u0_N-7R->F_N-4CF1sH->C_Ext-3C-R",
    group = 
"""
1 *1 C   u0         p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O   u0         {1,S} {3,S}
3 *3 C   u0         {2,S} {7,S} {8,[S,D,T,B,Q]}
4    F1s u0         {1,S}
5    F1s u0         {1,S}
6 *4 F1s u0         {1,S}
7    C   u[0,1,2,3] {3,S}
8    R!H ux         {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_N-3C-u0",
    group = 
"""
1 *1 C         u0       p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0       {1,S} {3,S}
3 *3 C         u[1,2,3] {2,S} {7,S}
4    [F1s,C,H] u0       {1,S}
5    [F1s,C,H] u0       {1,S}
6 *4 F1s       u0       {1,S}
7    R         u0       {3,S}
""",
    kinetics = None,
)

entry(
    index = 28,
    label = "Root_N-3C-u0_7R->O",
    group = 
"""
1 *1 C         u0       p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0       {1,S} {3,S}
3 *3 C         u[1,2,3] {2,S} {7,S}
4    [F1s,C,H] u0       {1,S}
5    [F1s,C,H] u0       {1,S}
6 *4 F1s       u0       {1,S}
7    O         u0       {3,S}
""",
    kinetics = None,
)

entry(
    index = 29,
    label = "Root_N-3C-u0_7R->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_9R!H->C",
    group = 
"""
1 *1 C         u0       p0 r0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0       r0 {1,S} {3,S}
3 *3 C         u[1,2,3] r0 {2,S} {7,S}
4    [F1s,C,H] u0       {1,S}
5    [F1s,C,H] u0       {1,S}
6 *4 F1s       u0       r0 {1,S}
7    O         u0       r0 {3,S} {8,[S,D,T,B,Q]}
8    C         ux       {7,[S,D,T,B,Q]} {9,S}
9    C         u0       r0 {8,S}
""",
    kinetics = None,
)

entry(
    index = 30,
    label = "Root_N-3C-u0_7R->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_N-9R!H->C",
    group = 
"""
1 *1 C         u0       p0 r0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0       r0 {1,S} {3,S}
3 *3 C         u[1,2,3] r0 {2,S} {7,S}
4    [F1s,C,H] u0       {1,S}
5    [F1s,C,H] u0       {1,S}
6 *4 F1s       u0       r0 {1,S}
7    O         u0       r0 {3,S} {8,[S,D,T,B,Q]}
8    C         ux       {7,[S,D,T,B,Q]} {9,S}
9    F         u0       r0 {8,S}
""",
    kinetics = None,
)

entry(
    index = 31,
    label = "Root_N-3C-u0_N-7R->O",
    group = 
"""
1 *1 C         u0       p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O         u0       {1,S} {3,S}
3 *3 C         u[1,2,3] {2,S} {7,S}
4    [F1s,C,H] u0       {1,S}
5    F1s       u0       {1,S}
6 *4 F1s       u0       {1,S}
7    [C,F]     u0       {3,S}
""",
    kinetics = None,
)

entry(
    index = 32,
    label = "Root_N-3C-u0_N-7R->O_4CF1sH->C",
    group = 
"""
1 *1 C     u0       p0 {2,S} {4,S} {5,S} {6,S}
2 *2 O     u0       {1,S} {3,S}
3 *3 C     u[1,2,3] {2,S} {7,S}
4    C     u0       {1,S}
5    F1s   u0       {1,S}
6 *4 F1s   u0       {1,S}
7    [C,F] u0       {3,S}
""",
    kinetics = None,
)

entry(
    index = 33,
    label = "Root_N-3C-u0_N-7R->O_4CF1sH->C_Ext-7CFH-R_Ext-7CFH-R_8R!H->C",
    group = 
"""
1 *1 C     u0       p0 r0 {2,S} {4,S} {5,S} {6,S}
2 *2 O     u0       r0 {1,S} {3,S}
3 *3 C     u[1,2,3] r0 {2,S} {7,S}
4    C     u0       r0 {1,S} {8,S}
5    F1s   u0       r0 {1,S}
6 *4 F1s   u0       {1,S}
7    [C,F] u0       r0 {3,S}
8    C     u0       r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 34,
    label = "Root_N-3C-u0_N-7R->O_4CF1sH->C_Ext-7CFH-R_Ext-7CFH-R_N-8R!H->C",
    group = 
"""
1 *1 C     u0       p0 r0 {2,S} {4,S} {5,S} {6,S}
2 *2 O     u0       r0 {1,S} {3,S}
3 *3 C     u[1,2,3] r0 {2,S} {7,S}
4    C     u0       r0 {1,S} {8,S}
5    F1s   u0       r0 {1,S}
6 *4 F1s   u0       {1,S}
7    [C,F] u0       r0 {3,S}
8    F     u0       r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 35,
    label = "Root_N-3C-u0_N-7R->O_N-4CF1sH->C",
    group = 
"""
1 *1 C     u0       p0 r0 {2,S} {4,S} {5,S} {6,S}
2 *2 O     u0       r0 {1,S} {3,S}
3 *3 C     u[1,2,3] r0 {2,S} {7,S}
4    F1s   u0       {1,S}
5    F1s   u0       r0 {1,S}
6 *4 F1s   u0       {1,S}
7    [C,F] u0       r0 {3,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_3C-u0
        L3: Root_3C-u0_7R->F
            L4: Root_3C-u0_7R->F_4CF1sH->F1s
                L5: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C
                    L6: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_5CF1sH->F1s
                        L7: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_5CF1sH->F1s_Ext-3C-R
                    L6: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_N-5CF1sH->F1s
                        L7: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_9R!H->C
                            L8: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_9R!H->C_Ext-3C-R
                        L7: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_N-9R!H->C
                            L8: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_N-9R!H->C_Ext-3C-R
                L5: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_N-Sp-8R!H-3C
                    L6: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_N-Sp-8R!H-3C_5CF1sH->F1s
                    L6: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_N-Sp-8R!H-3C_N-5CF1sH->F1s
                        L7: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_N-Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_9R!H->C
                        L7: Root_3C-u0_7R->F_4CF1sH->F1s_Ext-3C-R_N-Sp-8R!H-3C_N-5CF1sH->F1s_Ext-8R!H-R_Ext-8R!H-R_N-9R!H->C
            L4: Root_3C-u0_7R->F_N-4CF1sH->F1s
        L3: Root_3C-u0_N-7R->F
            L4: Root_3C-u0_N-7R->F_4CF1sH->C
                L5: Root_3C-u0_N-7R->F_4CF1sH->C_Ext-3C-R
                    L6: Root_3C-u0_N-7R->F_4CF1sH->C_Ext-3C-R_Ext-7CHO-R_Ext-7CHO-R_9R!H->C
                    L6: Root_3C-u0_N-7R->F_4CF1sH->C_Ext-3C-R_Ext-7CHO-R_Ext-7CHO-R_N-9R!H->C
                L5: Root_3C-u0_N-7R->F_4CF1sH->C_Ext-7CHO-R_Ext-7CHO-R_8R!H->C
                L5: Root_3C-u0_N-7R->F_4CF1sH->C_Ext-7CHO-R_Ext-7CHO-R_N-8R!H->C
            L4: Root_3C-u0_N-7R->F_N-4CF1sH->C
                L5: Root_3C-u0_N-7R->F_N-4CF1sH->C_Ext-3C-R
    L2: Root_N-3C-u0
        L3: Root_N-3C-u0_7R->O
            L4: Root_N-3C-u0_7R->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_9R!H->C
            L4: Root_N-3C-u0_7R->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_N-9R!H->C
        L3: Root_N-3C-u0_N-7R->O
            L4: Root_N-3C-u0_N-7R->O_4CF1sH->C
                L5: Root_N-3C-u0_N-7R->O_4CF1sH->C_Ext-7CFH-R_Ext-7CFH-R_8R!H->C
                L5: Root_N-3C-u0_N-7R->O_4CF1sH->C_Ext-7CFH-R_Ext-7CFH-R_N-8R!H->C
            L4: Root_N-3C-u0_N-7R->O_N-4CF1sH->C
"""
)

