#!/usr/bin/env python
# encoding: utf-8

name = "CO_CF_bond_dissociation/groups"
shortDesc = ""
longDesc = """
one carbon-oxygen and one carbon-fluorine bond is broken (although not on the same carbon). Oxygen and fluorine then bond to the "opposite" carbon. 


    *4F
    |
R - *1C - *2O - *3C - R      <-->   R - *1C = *2O    +   *4F - *3C - R
    |                                    |
    F                                    F

"""

template(reactants=["Root"], products=["CFO_", "R_F"], ownReverse=False)

reversible = True
reverse = "association_via_CO_CF_bond_formation"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*4', 1, '*1'],
    ['BREAK_BOND', '*2', 1, '*3'],
    ['CHANGE_BOND', '*1', 1, '*2'],
    ['FORM_BOND', '*4', 1, '*3'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 [F1s,C,H]  u0 {2,S}
2 *1 C u0 p0 {1,S} {3,S} {4,S} {5,S}
3 [F1s,C,H] u0 {2,S}
4 *4 F1s u0 {2,S}
5 *2 O u0 {2,S} {6,S}
6 *3 C u[0,1,2,3] {5,S} {7,S}
7 R u[0,1,2,3] {6,S}
""",
    kinetics = None,
)


         