#!/usr/bin/env python
# encoding: utf-8

name = "CF_Radical_Formation_2/groups"
shortDesc = ""
longDesc = """
*1F - *2C      <=>    *3R.     +     *2C. - *1F 
        |
      *3R
"""

template(reactants=["Root"], products=["R", "CF"], ownReverse=False)

reverse = "carbene_radical_addition_to_perfluorinated_radical"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*2', 1, '*3'],
    ['GAIN_RADICAL', '*2', 1],
    ['GAIN_RADICAL', '*3', 1],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 C   u0 p1 {2,S} {3,S}
2 *3 R   u0 {1,S}
3 *1 F1s u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-2R-R_4R!H->C",
    group = 
"""
1 *2 C   u0 p1 {2,S} {3,S}
2 *3 C   u0 {1,S} {4,S}
3 *1 F1s u0 {1,S}
4    C   u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-2R-R_N-4R!H->C",
    group = 
"""
1 *2 C   u0 p1 {2,S} {3,S}
2 *3 C   u0 {1,S} {4,S}
3 *1 F1s u0 {1,S}
4    F   u0 r0 {2,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-2R-R_4R!H->C
    L2: Root_Ext-2R-R_N-4R!H->C
"""
)

