#!/usr/bin/env python
# encoding: utf-8

name = "CF_Radical_Formation_2/groups"
shortDesc = ""
longDesc = """


*1F - *2C      <=>    *3R.     +     *2C. - *1F 
        |
      *3R
"""

template(reactants=["Root"], products=["R", "CF"], ownReverse=False)

reversible = True
reverse = "carbene_radical_addition_to_perfluorinated_radical"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*2', 1, '*3'],
    ['GAIN_RADICAL', '*2', 1],
    ['GAIN_RADICAL', '*3', 1],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1  *2 C u0 p1 {2,S} {3,S} 
2  *3 R u0 {1,S}
3  *1 F1s u0 {1,S}
""",
    kinetics = None,
)
