#!/usr/bin/env python
# encoding: utf-8

name = "Lactone_Formation/groups"
shortDesc = ""
longDesc = """
Perfluorinated carboxylic acid undergoes unimolecular decomposition to form HF and an alpha-lactone.                         
   *3C - *4F                                        *1O
    |                                               /  \
O = C            <=>       *2H - *4F      +    O = C - *3C  
    |
    *1O - *2H

"""

template(reactants=["Root"], products=["HF", "lactone"], ownReverse=False)

reversible = True
reverse = "lactone_to_PFCA"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*4', 1, '*3'],
    ['BREAK_BOND', '*2', 1, '*1'],
    ['FORM_BOND', '*1', 1, '*3'],
    ['FORM_BOND', '*2', 1, '*4'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 O u0 {2,S} {3,S}
2 *2 H u0 {1,S} 
3 C u0 {1,S} {4,D} {5,S}
4 O u0 {3,D}
5 *3 C u[0,1,2] {3,S} {6,S}
6 *4 F1s u0 {5,S}
""",
    kinetics = None,
)


         