#!/usr/bin/env python
# encoding: utf-8

name = "Lactone_Formation/groups"
shortDesc = ""
longDesc = """
Perfluorinated carboxylic acid undergoes unimolecular decomposition to form HF and an alpha-lactone.                         
   *3C - *4F                                        *1O
    |                                               /  O = C            <=>       *2H - *4F      +    O = C - *3C  
    |
    *1O - *2H
"""

template(reactants=["Root"], products=["HF", "lactone"], ownReverse=False)

reverse = "lactone_to_PFCA"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*4', 1, '*3'],
    ['BREAK_BOND', '*2', 1, '*1'],
    ['FORM_BOND', '*1', 1, '*3'],
    ['FORM_BOND', '*2', 1, '*4'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1    C   u0       {2,S} {3,S} {4,D}
2 *1 O   u0       {1,S} {5,S}
3 *3 C   u[0,1,2] {1,S} {6,S}
4    O   u0       {1,D}
5 *2 H   u0       {2,S}
6 *4 F1s u0       {3,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-3C-R_7R!H->O",
    group = 
"""
1    C   u0 {2,S} {3,S} {4,D}
2 *1 O   u0 {1,S} {5,S}
3 *3 C   u0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4    O   u0 {1,D}
5 *2 H   u0 {2,S}
6 *4 F1s u0 {3,S}
7    O   ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-3C-R_7R!H->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_9R!H->C",
    group = 
"""
1    C   u0 {2,S} {3,S} {4,D}
2 *1 O   u0 {1,S} {5,S}
3 *3 C   u0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4    O   u0 {1,D}
5 *2 H   u0 {2,S}
6 *4 F1s u0 {3,S}
7    O   ux {3,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
8    C   ux {7,[S,D,T,B,Q]} {9,S}
9    C   u0 {8,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_Ext-3C-R_7R!H->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_9R!H->C_Ext-9C-R_10R!H->C",
    group = 
"""
1     C   u0 r0 {2,S} {3,S} {4,D}
2  *1 O   u0 r0 {1,S} {5,S}
3  *3 C   u0 r0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4     O   u0 r0 {1,D}
5  *2 H   u0 r0 {2,S}
6  *4 F1s u0 r0 {3,S}
7     O   ux {3,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
8     C   ux {7,[S,D,T,B,Q]} {9,S}
9     C   u0 r0 {8,S} {10,S}
10    C   u0 r0 {9,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_Ext-3C-R_7R!H->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_9R!H->C_Ext-9C-R_N-10R!H->C",
    group = 
"""
1     C   u0 r0 {2,S} {3,S} {4,D}
2  *1 O   u0 r0 {1,S} {5,S}
3  *3 C   u0 r0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4     O   u0 r0 {1,D}
5  *2 H   u0 r0 {2,S}
6  *4 F1s u0 r0 {3,S}
7     O   ux {3,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
8     C   ux {7,[S,D,T,B,Q]} {9,S}
9     C   u0 r0 {8,S} {10,S}
10    F   u0 r0 {9,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_Ext-3C-R_7R!H->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_N-9R!H->C",
    group = 
"""
1    C   u0 r0 {2,S} {3,S} {4,D}
2 *1 O   u0 r0 {1,S} {5,S}
3 *3 C   u0 r0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4    O   u0 r0 {1,D}
5 *2 H   u0 r0 {2,S}
6 *4 F1s u0 r0 {3,S}
7    O   ux {3,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
8    C   ux {7,[S,D,T,B,Q]} {9,S}
9    F   u0 r0 {8,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_Ext-3C-R_N-7R!H->O",
    group = 
"""
1    C                      u0 {2,S} {3,S} {4,D}
2 *1 O                      u0 {1,S} {5,S}
3 *3 C                      u0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4    O                      u0 {1,D}
5 *2 H                      u0 {2,S}
6 *4 F1s                    u0 {3,S}
7    [C,Si,S,N,P,F,I,Br,Cl] ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_Ext-3C-R_N-7R!H->O_7BrCClFINPSSi->C",
    group = 
"""
1    C   u0 {2,S} {3,S} {4,D}
2 *1 O   u0 {1,S} {5,S}
3 *3 C   u0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4    O   u0 {1,D}
5 *2 H   u0 {2,S}
6 *4 F1s u0 {3,S}
7    C   ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_Ext-3C-R_N-7R!H->O_7BrCClFINPSSi->C_Ext-7C-R_8R!H->C",
    group = 
"""
1    C   u0 {2,S} {3,S} {4,D}
2 *1 O   u0 {1,S} {5,S}
3 *3 C   u0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4    O   u0 {1,D}
5 *2 H   u0 {2,S}
6 *4 F1s u0 {3,S}
7    C   ux {3,[S,D,T,B,Q]} {8,S}
8    C   u0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_Ext-3C-R_N-7R!H->O_7BrCClFINPSSi->C_Ext-7C-R_8R!H->C_Ext-8C-R_9R!H->C",
    group = 
"""
1    C   u0 r0 {2,S} {3,S} {4,D}
2 *1 O   u0 r0 {1,S} {5,S}
3 *3 C   u0 r0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4    O   u0 r0 {1,D}
5 *2 H   u0 r0 {2,S}
6 *4 F1s u0 r0 {3,S}
7    C   ux {3,[S,D,T,B,Q]} {8,S}
8    C   u0 r0 {7,S} {9,S}
9    C   u0 r0 {8,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_Ext-3C-R_N-7R!H->O_7BrCClFINPSSi->C_Ext-7C-R_8R!H->C_Ext-8C-R_N-9R!H->C",
    group = 
"""
1    C   u0 r0 {2,S} {3,S} {4,D}
2 *1 O   u0 r0 {1,S} {5,S}
3 *3 C   u0 r0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4    O   u0 r0 {1,D}
5 *2 H   u0 r0 {2,S}
6 *4 F1s u0 r0 {3,S}
7    C   ux {3,[S,D,T,B,Q]} {8,S}
8    C   u0 r0 {7,S} {9,S}
9    F   u0 r0 {8,S}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_Ext-3C-R_N-7R!H->O_7BrCClFINPSSi->C_Ext-7C-R_N-8R!H->C",
    group = 
"""
1    C   u0 r0 {2,S} {3,S} {4,D}
2 *1 O   u0 r0 {1,S} {5,S}
3 *3 C   u0 r0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4    O   u0 r0 {1,D}
5 *2 H   u0 r0 {2,S}
6 *4 F1s u0 r0 {3,S}
7    C   ux {3,[S,D,T,B,Q]} {8,S}
8    F   u0 r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_Ext-3C-R_N-7R!H->O_N-7BrCClFINPSSi->C",
    group = 
"""
1    C   u0 r0 {2,S} {3,S} {4,D}
2 *1 O   u0 r0 {1,S} {5,S}
3 *3 C   u0 r0 {1,S} {6,S} {7,[S,D,T,B,Q]}
4    O   u0 r0 {1,D}
5 *2 H   u0 r0 {2,S}
6 *4 F1s u0 r0 {3,S}
7    F   ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-3C-R_7R!H->O
        L3: Root_Ext-3C-R_7R!H->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_9R!H->C
            L4: Root_Ext-3C-R_7R!H->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_9R!H->C_Ext-9C-R_10R!H->C
            L4: Root_Ext-3C-R_7R!H->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_9R!H->C_Ext-9C-R_N-10R!H->C
        L3: Root_Ext-3C-R_7R!H->O_Ext-7O-R_Ext-8R!H-R_Ext-8R!H-R_Ext-8R!H-R_Ext-9R!H-R_N-9R!H->C
    L2: Root_Ext-3C-R_N-7R!H->O
        L3: Root_Ext-3C-R_N-7R!H->O_7BrCClFINPSSi->C
            L4: Root_Ext-3C-R_N-7R!H->O_7BrCClFINPSSi->C_Ext-7C-R_8R!H->C
                L5: Root_Ext-3C-R_N-7R!H->O_7BrCClFINPSSi->C_Ext-7C-R_8R!H->C_Ext-8C-R_9R!H->C
                L5: Root_Ext-3C-R_N-7R!H->O_7BrCClFINPSSi->C_Ext-7C-R_8R!H->C_Ext-8C-R_N-9R!H->C
            L4: Root_Ext-3C-R_N-7R!H->O_7BrCClFINPSSi->C_Ext-7C-R_N-8R!H->C
        L3: Root_Ext-3C-R_N-7R!H->O_N-7BrCClFINPSSi->C
"""
)

