#!/usr/bin/env python
# encoding: utf-8

name = "PFAS_Hydrolysis/groups"
shortDesc = ""
longDesc = """
Hydrolysis reaction. Water breaks into H and OH. OH breaks bond F-C, and F recombines with H. 

     *1F - *2C - R      +    *3H - *4O - H       <=>    *3H - *1F    +      H - *4O - *2C - R

     reactant 1               reactant 2
"""

template(reactants=["Root"], products=["HF", "OH_C_R"], ownReverse=False)

reverse = "PFAS_Hydrolysis_reverse"
reversible = True

reactantNum = 2

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*3', 1, '*1'],
    ['FORM_BOND', '*4', 1, '*2'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 C   u[0,1,2]   {3,S} {4,S}
2 *4 O   u0         {5,S} {6,S}
3 *1 F1s u0         {1,S}
4    R   u[0,1,2,3] {1,S}
5 *3 H   u0         {2,S}
6    H   u0         {2,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-1C-R_Ext-1C-R",
    group = 
"""
1 *2 C   u0 {3,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
2 *4 O   u0 {5,S} {6,S}
3 *1 F1s u0 {1,S}
4    R   u0 {1,S}
5 *3 H   u0 {2,S}
6    H   u0 {2,S}
7    R!H ux {1,[S,D,T,B,Q]}
8    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-1C-R_Ext-1C-R_4R->C",
    group = 
"""
1 *2 C   u0 {3,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
2 *4 O   u0 {5,S} {6,S}
3 *1 F1s u0 {1,S}
4    C   u0 {1,S}
5 *3 H   u0 {2,S}
6    H   u0 {2,S}
7    R!H ux {1,[S,D,T,B,Q]}
8    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_Ext-1C-R_Ext-1C-R_4R->C_Ext-4C-R_9R!H->C",
    group = 
"""
1 *2 C   u0 r0 {3,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
2 *4 O   u0 r0 {5,S} {6,S}
3 *1 F1s u0 r0 {1,S}
4    C   u0 r0 {1,S} {9,S}
5 *3 H   u0 {2,S}
6    H   u0 {2,S}
7    R!H ux {1,[S,D,T,B,Q]}
8    R!H ux {1,[S,D,T,B,Q]}
9    C   u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_Ext-1C-R_Ext-1C-R_4R->C_Ext-4C-R_N-9R!H->C",
    group = 
"""
1 *2 C   u0 r0 {3,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
2 *4 O   u0 r0 {5,S} {6,S}
3 *1 F1s u0 r0 {1,S}
4    C   u0 r0 {1,S} {9,S}
5 *3 H   u0 {2,S}
6    H   u0 {2,S}
7    R!H ux {1,[S,D,T,B,Q]}
8    R!H ux {1,[S,D,T,B,Q]}
9    F   u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_Ext-1C-R_Ext-1C-R_N-4R->C",
    group = 
"""
1 *2 C   u0 r0 {3,S} {4,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
2 *4 O   u0 r0 {5,S} {6,S}
3 *1 F1s u0 r0 {1,S}
4    F   u0 r0 {1,S}
5 *3 H   u0 {2,S}
6    H   u0 {2,S}
7    R!H ux {1,[S,D,T,B,Q]}
8    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_4R->C",
    group = 
"""
1 *2 C   u[0,1,2]   {3,S} {4,S}
2 *4 O   u0         {5,S} {6,S}
3 *1 F1s u0         {1,S}
4    C   u[0,1,2,3] {1,S}
5 *3 H   u0         {2,S}
6    H   u0         {2,S}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_4R->C_Ext-4C-R_7R!H->C",
    group = 
"""
1 *2 C   u[0,1,2]   {3,S} {4,S}
2 *4 O   u0         {5,S} {6,S}
3 *1 F1s u0         {1,S}
4    C   u[0,1,2,3] {1,S} {7,S}
5 *3 H   u0         {2,S}
6    H   u0         {2,S}
7    C   u0         {4,S}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_4R->C_Ext-4C-R_7R!H->C_Ext-7C-R_8R!H->C",
    group = 
"""
1 *2 C   u[0,1,2]   {3,S} {4,S}
2 *4 O   u0         {5,S} {6,S}
3 *1 F1s u0         {1,S}
4    C   u[0,1,2,3] {1,S} {7,S}
5 *3 H   u0         {2,S}
6    H   u0         {2,S}
7    C   u0         r0 {4,S} {8,S}
8    C   u0         r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_4R->C_Ext-4C-R_7R!H->C_Ext-7C-R_N-8R!H->C",
    group = 
"""
1 *2 C   u[0,1,2]   {3,S} {4,S}
2 *4 O   u0         {5,S} {6,S}
3 *1 F1s u0         {1,S}
4    C   u[0,1,2,3] {1,S} {7,S}
5 *3 H   u0         {2,S}
6    H   u0         {2,S}
7    C   u0         r0 {4,S} {8,S}
8    F   u0         r0 {7,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_4R->C_Ext-4C-R_N-7R!H->C",
    group = 
"""
1 *2 C   u[0,1,2]   {3,S} {4,S}
2 *4 O   u0         {5,S} {6,S}
3 *1 F1s u0         {1,S}
4    C   u[0,1,2,3] {1,S} {7,S}
5 *3 H   u0         {2,S}
6    H   u0         {2,S}
7    F   u0         r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_N-4R->C",
    group = 
"""
1 *2 C   u[0,1,2]   {3,S} {4,S}
2 *4 O   u0         {5,S} {6,S}
3 *1 F1s u0         {1,S}
4    F   u[0,1,2,3] {1,S}
5 *3 H   u0         {2,S}
6    H   u0         {2,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-1C-R_Ext-1C-R
        L3: Root_Ext-1C-R_Ext-1C-R_4R->C
            L4: Root_Ext-1C-R_Ext-1C-R_4R->C_Ext-4C-R_9R!H->C
            L4: Root_Ext-1C-R_Ext-1C-R_4R->C_Ext-4C-R_N-9R!H->C
        L3: Root_Ext-1C-R_Ext-1C-R_N-4R->C
    L2: Root_4R->C
        L3: Root_4R->C_Ext-4C-R_7R!H->C
            L4: Root_4R->C_Ext-4C-R_7R!H->C_Ext-7C-R_8R!H->C
            L4: Root_4R->C_Ext-4C-R_7R!H->C_Ext-7C-R_N-8R!H->C
        L3: Root_4R->C_Ext-4C-R_N-7R!H->C
    L2: Root_N-4R->C
"""
)

