#!/usr/bin/env python
# encoding: utf-8

name = "PFAS_Hydrolysis/groups"
shortDesc = ""
longDesc = """
Hydrolysis reaction. Water breaks into H and OH. OH breaks bond F-C, and F recombines with H. 

     *1F - *2C - R      +    *3H - *4O - H       <=>    *3H - *1F    +      H - *4O - *2C - R

     reactant 1               reactant 2       

"""

template(reactants=["Root"], products=["HF", "OH_C_R"], ownReverse=False)

reversible = True
         
reactantNum = 2

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*3', 1, '*1'],
    ['FORM_BOND', '*4', 1, '*2'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 F1s u0 {2,S}
2 *2 C u[0,1,2] {1,S} {3,S}
3 R u[0,1,2,3] {2,S}
4 *3 H u0 {5,S}
5 *4 O u0 {4,S} {6,S}
6 H u0 {5,S}
""",
    kinetics = None,
)


         