#!/usr/bin/env python
# encoding: utf-8

name = "CO2_Elimination_From_PFCA_Radical/groups"
shortDesc = ""
longDesc = """

*1H - *2O 
        |
       *3C = *4O    <=>    *2O = *3C = *4O   +  *1H - *5C.   
        |
 F -  *5C.
"""

template(reactants=["Root"], products=["CFO_", "R_F"], ownReverse=False)

reversible = True
reverse = "association_via_CO_CF_bond_formation"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*5'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['FORM_BOND', '*1', 1, '*5'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 H u0 {2,S}
2 *2 O u0 {1,S} {3,S}
3 *3 C u0 {2,S} {4,D} {5,S}
4 *4 O u0 {3,D}
5 *5 C u1 {3,S} {6,S}
6 F1s u0 {5,S}
""",
    kinetics = None,
)


         