#!/usr/bin/env python
# encoding: utf-8

name = "Lactone_to_Perfluoroalkene/groups"
shortDesc = ""
longDesc = """
*6C - *7F
     |       
F - *1C - *2C = *3O  <=>  *4O = *2C = *3O  +  F - *6C = *1C - *7F
       \  /
       *4O
"""

template(reactants=["Root"], products=["CO2", "perfluoroalkene"], ownReverse=False)

reverse = "CO2_addition_into_perfluoroalkene"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*6', 1, '*7'],
    ['BREAK_BOND', '*2', 1, '*1'],
    ['BREAK_BOND', '*4', 1, '*1'],
    ['CHANGE_BOND', '*4', 1, '*2'],
    ['FORM_BOND', '*7', 1, '*1'],
    ['CHANGE_BOND', '*6', 1, '*1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 C   u0 {2,S} {3,S} {4,S} {5,S}
2 *2 C   u0 {1,S} {3,S} {6,D}
3 *4 O   u0 {1,S} {2,S}
4 *6 C   u0 {1,S} {7,S}
5    F1s u0 {1,S}
6 *3 O   u0 {2,D}
7 *7 F1s u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-4C-R_8R!H->C",
    group = 
"""
1 *1 C   u0 r1 {2,S} {3,S} {4,S} {5,S}
2 *2 C   u0 r1 {1,S} {3,S} {6,D}
3 *4 O   u0 r1 {1,S} {2,S}
4 *6 C   u0 {1,S} {7,S} {8,S}
5    F1s u0 {1,S}
6 *3 O   u0 {2,D}
7 *7 F1s u0 {4,S}
8    C   u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-4C-R_N-8R!H->C",
    group = 
"""
1 *1 C   u0 r1 {2,S} {3,S} {4,S} {5,S}
2 *2 C   u0 r1 {1,S} {3,S} {6,D}
3 *4 O   u0 r1 {1,S} {2,S}
4 *6 C   u0 {1,S} {7,S} {8,S}
5    F1s u0 {1,S}
6 *3 O   u0 {2,D}
7 *7 F1s u0 {4,S}
8    F   u0 r0 {4,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-4C-R_8R!H->C
    L2: Root_Ext-4C-R_N-8R!H->C
"""
)

