#!/usr/bin/env python
# encoding: utf-8

name = "Lactone_to_Perfluoroalkene/groups"
shortDesc = ""
longDesc = """


    *6C - *7F
     |       
F - *1C - *2C = *3O  <=>  *4O = *2C = *3O  +  F - *6C = *1C - *7F
       \  /
       *4O
"""

template(reactants=["Root"], products=["CO2", "perfluoroalkene"], ownReverse=False)

reversible = True
reverse = "CO2_addition_into_perfluoroalkene"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*6', 1, '*7'],
    ['BREAK_BOND', '*2', 1, '*1'],
    ['BREAK_BOND', '*4', 1, '*1'],
    ['CHANGE_BOND', '*4', 1, '*2'],
    ['FORM_BOND', '*7', 1, '*1'],
    ['CHANGE_BOND', '*6', 1, '*1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 C u0 {5,S} {6,S} {2,S} {4,S}
2 *2 C u0 {3,D} {4,S} {1,S}
3 *3 O u0 {2,D}
4 *4 O u0 {1,S} {2,S}
5 F1s u0 {1,S}
6 *6 C u0 {7,S} {1,S}
7 *7 F1s u0 {6,S}
""",
    kinetics = None,
)
