#!/usr/bin/env python
# encoding: utf-8

name = "OF_Radical_Formation/groups"
shortDesc = ""
longDesc = """


*1O. - *2O - *3C - *4F    <=>    *4F - *1O.   +    *2O = *3C 


"""

template(reactants=["Root"], products=["FO", "carbonyl"], ownReverse=False)

reversible = True
reverse = "FO_carbonyl_recombination"
         
reactantNum = 1

productNum = 2
         
autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['FORM_BOND', '*4', 1, '*1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 O u1 {2,S}
2 *2 O u0 {1,S} {3,S}
3 *3 C u[0,1,2] {2,S} {4,S}
4 *4 F u0 {3,S}
""",
    kinetics = None,
)
