#!/usr/bin/env python
# encoding: utf-8

name = "OF_Radical_Formation/groups"
shortDesc = ""
longDesc = """
*1O. - *2O - *3C - *4F    <=>    *4F - *1O.   +    *2O = *3C
"""

template(reactants=["Root"], products=["FO", "carbonyl"], ownReverse=False)

reverse = "FO_carbonyl_recombination"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['FORM_BOND', '*4', 1, '*1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 O u0       {2,S} {3,S}
2 *3 C u[0,1,2] {1,S} {4,S}
3 *1 O u1       {1,S}
4 *4 F u0       {2,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-2C-R_5R!H->C",
    group = 
"""
1 *2 O u0       {2,S} {3,S}
2 *3 C u[0,1,2] {1,S} {4,S} {5,S}
3 *1 O u1       {1,S}
4 *4 F u0       {2,S}
5    C u0       {2,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-2C-R_5R!H->C_Ext-5C-R_6R!H->C",
    group = 
"""
1 *2 O u0       {2,S} {3,S}
2 *3 C u[0,1,2] {1,S} {4,S} {5,S}
3 *1 O u1       {1,S}
4 *4 F u0       {2,S}
5    C u0       r0 {2,S} {6,S}
6    C u0       r0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_Ext-2C-R_5R!H->C_Ext-5C-R_N-6R!H->C",
    group = 
"""
1 *2 O u0       {2,S} {3,S}
2 *3 C u[0,1,2] {1,S} {4,S} {5,S}
3 *1 O u1       {1,S}
4 *4 F u0       {2,S}
5    C u0       r0 {2,S} {6,S}
6    F u0       r0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_Ext-2C-R_N-5R!H->C",
    group = 
"""
1 *2 O u0       {2,S} {3,S}
2 *3 C u[0,1,2] {1,S} {4,S} {5,S}
3 *1 O u1       {1,S}
4 *4 F u0       {2,S}
5    F u0       r0 {2,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-2C-R_5R!H->C
        L3: Root_Ext-2C-R_5R!H->C_Ext-5C-R_6R!H->C
        L3: Root_Ext-2C-R_5R!H->C_Ext-5C-R_N-6R!H->C
    L2: Root_Ext-2C-R_N-5R!H->C
"""
)

